# Copied from gliner2 2.0.0 ((package)), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
__version__ = "2.0.0"
