# Copied from gliner2 2.0.0 (models/boundary/constants.py), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
"""Numeric constants shared by the boundary head."""

# A finite masking sentinel representable by fp16, bf16, and fp32. Several
# proposal terms may be added before masking; using dtype minima can overflow.
MASK_LOGIT = -1.0e4
