# Copied from gliner2 2.0.0 (models/boundary/relations.py), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
"""Sparse, typed relation extraction for the boundary architecture.

Relations reuse the entity mention candidates rather than introducing a second
extraction representation. Pair generation is *typed and capped*: for each
relation type we keep only the top-``Rh`` head-typed and top-``Rt`` tail-typed
mentions and score their capped cross product. Work is therefore ``O(Rh*Rt)``
per relation type with fixed caps — never the ``O(N^2)`` all-pairs matrix.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Sequence, Tuple

from cognee.tasks.graph.gliner_demo.onnx import _tensor as torch
from cognee.tasks.graph.gliner_demo.onnx._tensor import nn
from cognee.tasks.graph.gliner_demo.onnx._tensor import functional as F

from cognee.tasks.graph.gliner_demo.onnx._gliner2.models.base import QueryLayout
from cognee.tasks.graph.gliner_demo.onnx._gliner2.models.outputs import CandidateTensorBatch
from cognee.tasks.graph.gliner_demo.onnx._gliner2.models.boundary.validation import safe_relation_indices


@dataclass(frozen=True)
class RelationProposalSettings:
    heads_per_relation: int = 32
    tails_per_relation: int = 32
    pair_cap: int = 128
    argument_threshold: float = 0.0


@dataclass(frozen=True)
class RelationTypeSpec:
    """A relation type with its allowed head/tail entity queries."""

    relation_type: str
    head_query_ids: Tuple[int, ...]
    tail_query_ids: Tuple[int, ...]
    allow_self: bool = False


@dataclass
class RelationPairBatch:
    """Flattened typed relation-pair proposals across a batch.

    All index tensors have shape ``[P]`` (P = total proposed pairs). ``*_end``
    are half-open (last covered token is ``end - 1``).
    """

    batch_index: torch.LongTensor
    relation_index: torch.LongTensor
    head_start: torch.LongTensor
    head_end: torch.LongTensor
    tail_start: torch.LongTensor
    tail_end: torch.LongTensor
    head_prob: torch.Tensor
    tail_prob: torch.Tensor
    pair_mask: torch.BoolTensor | None = None
    head_keys: List[Tuple[str, int, int]] = field(default_factory=list)
    tail_keys: List[Tuple[str, int, int]] = field(default_factory=list)
    relation_types: List[str] = field(default_factory=list)

    def __len__(self) -> int:
        return int(self.batch_index.shape[0])


def _query_type(layout: QueryLayout, query_id: int) -> str:
    try:
        return layout.query(query_id).role_name
    except KeyError:
        return str(query_id)


class TypedRelationPairGenerator:
    """Generate typed, capped relation pairs from entity candidates."""

    def __init__(self, settings: RelationProposalSettings | None = None) -> None:
        self.settings = settings or RelationProposalSettings()

    def generate(
        self,
        candidates: CandidateTensorBatch,
        query_layouts: Sequence[QueryLayout],
        relation_schema: Sequence[RelationTypeSpec],
        *,
        compact: bool = True,
    ) -> RelationPairBatch:
        schemas = [relation_schema for _ in range(candidates.indices.shape[0])]
        return self.generate_batched(
            candidates, query_layouts, schemas, compact=compact
        )

    def generate_batched(
        self,
        candidates: CandidateTensorBatch,
        query_layouts: Sequence[QueryLayout],
        relation_schemas: Sequence[Sequence[RelationTypeSpec]],
        *,
        compact: bool = False,
        routing: tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]
        | None = None,
    ) -> RelationPairBatch:
        """Generate all ``[B,R,pair_cap]`` proposals with tensor operations.

        ``compact=False`` is the synchronization-free training representation:
        invalid padded proposals remain present and are identified by
        :attr:`RelationPairBatch.pair_mask`. ``compact=True`` is the
        backward-compatible decode representation and materializes Python keys.
        """
        s = self.settings
        device = candidates.indices.device
        bsz, queries, cand_count = candidates.valid_mask.shape
        rel_count = (
            routing[0].shape[1]
            if routing is not None
            else max((len(x) for x in relation_schemas), default=0)
        )
        if rel_count == 0:
            empty = torch.zeros(0, dtype=torch.long, device=device)
            return RelationPairBatch(
                empty, empty, empty, empty, empty, empty,
                candidates.pair_logits.new_zeros(0),
                candidates.pair_logits.new_zeros(0),
                pair_mask=torch.zeros(0, dtype=torch.bool, device=device),
            )

        if routing is not None:
            head_member, tail_member, relation_valid, allow_self = routing
            head_member = head_member.to(device=device)
            tail_member = tail_member.to(device=device)
            relation_valid = relation_valid.to(device=device)
            allow_self = allow_self.to(device=device)
        else:
            # Decode-only fallback. Training supplies collator-built routing and
            # never performs device scalar writes in this loop.
            head_member = torch.zeros(
                bsz, rel_count, queries, dtype=torch.bool, device=device
            )
            tail_member = torch.zeros_like(head_member)
            relation_valid = torch.zeros(
                bsz, rel_count, dtype=torch.bool, device=device
            )
            allow_self = torch.zeros_like(relation_valid)
            for batch_index, schemas in enumerate(relation_schemas):
                for relation_index, spec in enumerate(schemas):
                    relation_valid[batch_index, relation_index] = True
                    allow_self[batch_index, relation_index] = spec.allow_self
                    valid_h = [q for q in spec.head_query_ids if 0 <= q < queries]
                    valid_t = [q for q in spec.tail_query_ids if 0 <= q < queries]
                    if valid_h:
                        head_member[batch_index, relation_index, valid_h] = True
                    if valid_t:
                        tail_member[batch_index, relation_index, valid_t] = True

        probs = torch.sigmoid(candidates.pair_logits)
        base_valid = candidates.valid_mask & candidates.query_mask.unsqueeze(-1)
        flat_prob = probs.reshape(bsz, 1, queries * cand_count).expand(-1, rel_count, -1)
        flat_valid = base_valid.reshape(bsz, 1, -1).expand(-1, rel_count, -1)
        head_valid = flat_valid & head_member.unsqueeze(-1).expand(
            -1, -1, -1, cand_count
        ).reshape(bsz, rel_count, -1)
        tail_valid = flat_valid & tail_member.unsqueeze(-1).expand(
            -1, -1, -1, cand_count
        ).reshape(bsz, rel_count, -1)
        threshold = flat_prob >= s.argument_threshold
        head_valid &= threshold
        tail_valid &= threshold
        floor = torch.finfo(flat_prob.dtype).min
        flat_spans = candidates.indices.reshape(bsz, queries * cand_count, 2)

        def select(valid: torch.BoolTensor, requested: int):
            take = min(requested, queries * cand_count)
            secondary = torch.arange(
                queries * cand_count, device=device
            ).view(1, 1, -1).expand(bsz, rel_count, -1)
            end_key = flat_spans[..., 1].unsqueeze(1).expand(
                -1, rel_count, -1
            )
            end_order = torch.argsort(
                end_key.gather(-1, secondary), dim=-1, stable=True
            )
            secondary = secondary.gather(-1, end_order)
            start_key = flat_spans[..., 0].unsqueeze(1).expand(
                -1, rel_count, -1
            )
            start_order = torch.argsort(
                start_key.gather(-1, secondary), dim=-1, stable=True
            )
            secondary = secondary.gather(-1, start_order)
            ordered_score = flat_prob.gather(-1, secondary)
            ordered_valid = valid.gather(-1, secondary)
            rank_in_secondary = torch.argsort(
                ordered_score.masked_fill(~ordered_valid, floor),
                dim=-1, descending=True, stable=True,
            )[..., :take]
            ranked = secondary.gather(-1, rank_in_secondary)
            selected_valid = valid.gather(-1, ranked)
            selected_prob = flat_prob.gather(-1, ranked)
            if take < requested:
                pad = requested - take
                ranked = F.pad(ranked, (0, pad))
                selected_valid = F.pad(selected_valid, (0, pad), value=False)
                selected_prob = F.pad(selected_prob, (0, pad))
            qslot = torch.div(ranked, cand_count, rounding_mode="floor")
            cslot = ranked - qslot * cand_count
            qslot = qslot.clamp(0, queries - 1)
            cslot = cslot.clamp(0, cand_count - 1)
            batch = torch.arange(bsz, device=device)[:, None, None]
            spans = candidates.indices[batch, qslot, cslot]
            return selected_prob, qslot, spans, selected_valid

        hp, hq, hspan, hvalid = select(head_valid, s.heads_per_relation)
        tp, tq, tspan, tvalid = select(tail_valid, s.tails_per_relation)
        pair_score = hp.unsqueeze(-1) * tp.unsqueeze(-2)
        pair_valid = hvalid.unsqueeze(-1) & tvalid.unsqueeze(-2)
        same_span = (hspan.unsqueeze(-2) == tspan.unsqueeze(-3)).all(-1)
        pair_valid &= allow_self[..., None, None] | ~same_span
        pair_valid &= relation_valid[..., None, None]
        flat_pair_score = pair_score.flatten(2)
        flat_pair_valid = pair_valid.flatten(2)
        take = min(s.pair_cap, flat_pair_score.shape[-1])
        keep = torch.argsort(
            flat_pair_score.masked_fill(~flat_pair_valid, floor),
            dim=-1, descending=True, stable=True,
        )[..., :take]
        kept_valid = flat_pair_valid.gather(-1, keep)
        if take < s.pair_cap:
            keep = F.pad(keep, (0, s.pair_cap - take))
            kept_valid = F.pad(kept_valid, (0, s.pair_cap - take), value=False)
        hi = torch.div(keep, s.tails_per_relation, rounding_mode="floor")
        ti = keep - hi * s.tails_per_relation
        hi = hi.clamp(0, s.heads_per_relation - 1)
        ti = ti.clamp(0, s.tails_per_relation - 1)

        def gather_selected(values: torch.Tensor, index: torch.LongTensor):
            return values.gather(
                2, index.clamp(0, values.shape[2] - 1).unsqueeze(-1).expand(*index.shape, values.shape[-1])
            )

        hs = gather_selected(hspan, hi)
        ts = gather_selected(tspan, ti)
        hp_out = hp.gather(2, hi.clamp(0, hp.shape[2] - 1))
        tp_out = tp.gather(2, ti.clamp(0, tp.shape[2] - 1))
        hq_out = hq.gather(2, hi.clamp(0, hq.shape[2] - 1))
        tq_out = tq.gather(2, ti.clamp(0, tq.shape[2] - 1))
        bi = torch.arange(bsz, device=device)[:, None, None].expand_as(keep)
        ri = torch.arange(rel_count, device=device)[None, :, None].expand_as(keep)

        flat_mask = kept_valid.reshape(-1)
        tensors = [
            bi.reshape(-1), ri.reshape(-1), hs[..., 0].reshape(-1),
            hs[..., 1].reshape(-1), ts[..., 0].reshape(-1),
            ts[..., 1].reshape(-1), hp_out.reshape(-1), tp_out.reshape(-1),
            hq_out.reshape(-1), tq_out.reshape(-1),
        ]
        if compact:
            tensors = [value[flat_mask] for value in tensors]
            flat_mask = torch.ones_like(tensors[0], dtype=torch.bool)
        out = RelationPairBatch(
            batch_index=tensors[0], relation_index=tensors[1],
            head_start=tensors[2], head_end=tensors[3],
            tail_start=tensors[4], tail_end=tensors[5],
            head_prob=tensors[6], tail_prob=tensors[7],
            pair_mask=flat_mask,
        )
        if compact:
            # Decode-only metadata: Python conversion is intentionally absent
            # from the training representation.
            for index in range(len(out)):
                batch_index = int(out.batch_index[index])
                relation_index = int(out.relation_index[index])
                spec = relation_schemas[batch_index][relation_index]
                layout = (
                    query_layouts[batch_index]
                    if batch_index < len(query_layouts) else None
                )
                out.relation_types.append(spec.relation_type)
                # Endpoint type names are only presentation metadata. For the
                # common single-type schema use the declared query directly.
                hquery = int(tensors[8][index])
                tquery = int(tensors[9][index])
                out.head_keys.append((
                    _query_type(layout, hquery) if layout is not None else str(hquery),
                    int(out.head_start[index]), int(out.head_end[index]),
                ))
                out.tail_keys.append((
                    _query_type(layout, tquery) if layout is not None else str(tquery),
                    int(out.tail_start[index]), int(out.tail_end[index]),
                ))
        return out


class SparseRelationScorer(nn.Module):
    """Score proposed relation pairs from boundary endpoint states.

    Uses only local features (four endpoint boundary states, the relation query,
    relative order and a normalized distance) — no dense pair matrix.
    """

    def __init__(
        self,
        hidden_size: int,
        dropout: float = 0.0,
        relation_query_dim: int | None = None,
        use_biaffine_content: bool = False,
    ) -> None:
        super().__init__()
        self.hidden_size = hidden_size
        self.relation_query_dim = relation_query_dim or hidden_size
        self.use_biaffine_content = use_biaffine_content
        in_dim = 4 * hidden_size + self.relation_query_dim + 2
        self.mlp = nn.Sequential(
            nn.Linear(in_dim, hidden_size),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, 1),
        )
        if use_biaffine_content:
            self.head_content_projection = nn.Linear(hidden_size, hidden_size)
            self.tail_content_projection = nn.Linear(hidden_size, hidden_size)
            self.relation_content_gate = nn.Linear(
                self.relation_query_dim, hidden_size
            )
            self.content_linear = nn.Linear(
                2 * hidden_size + self.relation_query_dim, 1
            )

    def forward(
        self,
        boundary_states: torch.Tensor,          # [B, L, H]
        relation_query_states: torch.Tensor,    # [B, R, H]
        entity_candidates: CandidateTensorBatch,  # (unused indices carrier; kept for API)
        relation_pairs: RelationPairBatch,
    ) -> torch.Tensor:
        if len(relation_pairs) == 0:
            return boundary_states.new_zeros(0)

        batch_count = min(
            boundary_states.shape[0], relation_query_states.shape[0]
        )
        if batch_count <= 0 or relation_query_states.shape[1] <= 0:
            return boundary_states.new_zeros(len(relation_pairs))
        batch_valid = (
            (relation_pairs.batch_index >= 0)
            & (relation_pairs.batch_index < batch_count)
        )
        b = relation_pairs.batch_index.clamp(0, batch_count - 1)
        relation_index, relation_valid = safe_relation_indices(
            relation_pairs.relation_index,
            relation_query_states.shape[1],
        )
        pair_valid = batch_valid & relation_valid
        if relation_pairs.pair_mask is not None:
            pair_valid &= relation_pairs.pair_mask
        length = boundary_states.shape[1]

        def gather(pos: torch.Tensor) -> torch.Tensor:
            pos = pos.clamp(0, max(length - 1, 0))
            return boundary_states[b, pos]

        h_start = gather(relation_pairs.head_start)
        h_end = gather(relation_pairs.head_end - 1)
        t_start = gather(relation_pairs.tail_start)
        t_end = gather(relation_pairs.tail_end - 1)
        rel = relation_query_states[b, relation_index]

        # Positional features originate from integer indices; create them in
        # the activation dtype before concatenating with encoder states so the
        # relation MLP remains compatible with FP16/BF16 models.
        delta = (relation_pairs.tail_start - relation_pairs.head_start).to(
            boundary_states.dtype
        )
        order = torch.sign(delta).unsqueeze(-1)
        dist = (delta.abs() / float(max(length, 1))).unsqueeze(-1)

        feats = torch.cat([h_start, h_end, t_start, t_end, rel, order, dist], dim=-1)
        score = self.mlp(feats).squeeze(-1)
        if self.use_biaffine_content:
            prefix = torch.cat(
                (
                    boundary_states.new_zeros(
                        boundary_states.shape[0], 1, self.hidden_size
                    ),
                    boundary_states.float().cumsum(1).to(boundary_states.dtype),
                ),
                dim=1,
            )

            def pool(start: torch.Tensor, end: torch.Tensor) -> torch.Tensor:
                span_sum = prefix[b, end.clamp(0, length)] - prefix[
                    b, start.clamp(0, length)
                ]
                width = (end - start).clamp_min(1).unsqueeze(-1).to(span_sum.dtype)
                return span_sum / width

            head_content = self.head_content_projection(
                pool(relation_pairs.head_start, relation_pairs.head_end)
            )
            tail_content = self.tail_content_projection(
                pool(relation_pairs.tail_start, relation_pairs.tail_end)
            )
            gate = torch.sigmoid(self.relation_content_gate(rel))
            biaffine = (
                head_content * gate * tail_content
            ).sum(-1) / (self.hidden_size ** 0.5)
            linear = self.content_linear(
                torch.cat((head_content, tail_content, rel), dim=-1)
            ).squeeze(-1)
            score = score + biaffine + linear
        return score.masked_fill(~pair_valid, 0.0)


__all__ = [
    "RelationProposalSettings",
    "RelationTypeSpec",
    "RelationPairBatch",
    "TypedRelationPairGenerator",
    "SparseRelationScorer",
]
