# Copied from gliner2 2.0.0 (models/boundary/validation.py), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
"""Central index contracts for boundary-model tensor operations."""

from __future__ import annotations

from typing import Optional, Sequence, Tuple

from cognee.tasks.graph.gliner_demo.onnx import _tensor as torch


def safe_query_ids(
    query_ids: torch.LongTensor,
    *query_counts: int,
) -> Tuple[torch.LongTensor, torch.BoolTensor]:
    """Clamp query IDs to dimensions shared by every indexed query tensor."""
    if not query_counts or min(query_counts) <= 0:
        valid = torch.zeros_like(query_ids, dtype=torch.bool)
        return torch.zeros_like(query_ids), valid
    upper = min(int(count) for count in query_counts) - 1
    valid = (query_ids >= 0) & (query_ids <= upper)
    return query_ids.clamp(min=0, max=upper), valid


def safe_relation_indices(
    relation_indices: torch.LongTensor,
    relation_count: int,
) -> Tuple[torch.LongTensor, torch.BoolTensor]:
    """Return gather-safe relation indices and their original validity mask."""
    if relation_count <= 0:
        return (
            torch.zeros_like(relation_indices),
            torch.zeros_like(relation_indices, dtype=torch.bool),
        )
    valid = (relation_indices >= 0) & (relation_indices < relation_count)
    return relation_indices.clamp(min=0, max=relation_count - 1), valid


def filter_match_indices(
    indices: Sequence[torch.LongTensor],
    shape: Sequence[int],
    *,
    instance_mask: Optional[torch.BoolTensor] = None,
) -> Tuple[torch.LongTensor, ...]:
    """Drop unsafe advanced-index tuples before a CUDA indexing kernel.

    ``indices`` and ``shape`` describe an N-dimensional advanced index.  When
    supplied, ``instance_mask`` is indexed by the first three coordinates and
    rejects padded record-instance rows.
    """
    if len(indices) != len(shape):
        raise ValueError(
            f"index rank {len(indices)} does not match tensor rank {len(shape)}"
        )
    if not indices:
        return ()
    lengths = {int(index.numel()) for index in indices}
    if len(lengths) != 1:
        raise ValueError("advanced-index tensors must have equal lengths")

    valid = torch.ones_like(indices[0], dtype=torch.bool)
    for index, size in zip(indices, shape):
        valid &= (index >= 0) & (index < int(size))

    if instance_mask is not None and valid.any():
        if len(indices) < 3:
            raise ValueError("instance_mask requires at least three index axes")
        if any(int(size) <= 0 for size in instance_mask.shape):
            return tuple(index[:0] for index in indices)
        for index, size in zip(indices[:3], instance_mask.shape):
            valid &= (index >= 0) & (index < int(size))
        safe = tuple(
            index.clamp(min=0, max=max(int(size) - 1, 0))
            for index, size in zip(indices[:3], instance_mask.shape)
        )
        valid &= instance_mask[safe]
    return tuple(index[valid] for index in indices)


def validate_masked_spans(
    spans: torch.LongTensor,
    mask: torch.BoolTensor,
    text_lengths: torch.LongTensor,
    *,
    name: str,
) -> None:
    """Validate active half-open spans against each sample's text length."""
    if spans.shape[:-1] != mask.shape or spans.shape[-1] != 2:
        raise ValueError(
            f"{name}: spans {tuple(spans.shape)} and mask {tuple(mask.shape)} "
            "are incompatible"
        )
    if spans.shape[0] != text_lengths.numel():
        raise ValueError(
            f"{name}: batch size {spans.shape[0]} does not match "
            f"{text_lengths.numel()} text lengths"
        )
    lengths = text_lengths.to(spans.device).reshape(
        spans.shape[0], *([1] * (spans.ndim - 2))
    )
    starts, ends = spans[..., 0], spans[..., 1]
    invalid = mask & (
        (starts < 0)
        | (ends <= starts)
        | (ends > lengths)
    )
    if invalid.any().item():
        first = invalid.nonzero(as_tuple=False)[0].tolist()
        location = tuple(int(value) for value in first)
        pair = spans[tuple(first)].detach().cpu().tolist()
        sample = int(first[0])
        raise ValueError(
            f"{name}: invalid active span {pair} at {location} for "
            f"text length {int(text_lengths[sample])}"
        )


def validate_candidate_indices(
    indices: torch.LongTensor,
    valid_mask: torch.BoolTensor,
    text_lengths: torch.LongTensor,
) -> None:
    """Validate active candidate spans before downstream indexing."""
    validate_masked_spans(
        indices,
        valid_mask,
        text_lengths,
        name="candidate_indices",
    )


__all__ = [
    "filter_match_indices",
    "safe_query_ids",
    "safe_relation_indices",
    "validate_candidate_indices",
    "validate_masked_spans",
]
