"""Regenerate ``_gliner2`` from the installed gliner2 (dev tool; needs gliner2).

    python -m cognee.tasks.graph.gliner_demo.onnx.vendor_gliner2

Copies the gliner2 modules on the entities + relations inference path, byte for
byte except for import lines: ``torch`` resolves to ``_tensor`` (numpy),
``transformers`` to ``_hf``, ``gliner2`` to the copy. From ``model.py``, which
is mostly torch model classes, only the inference helpers are extracted.
gliner2 is Apache-2.0; every copied file keeps a header naming its origin.
"""

from __future__ import annotations

import ast
import re
from importlib.metadata import version
from pathlib import Path

PACKAGE = "cognee.tasks.graph.gliner_demo.onnx"
DEFAULT_OUT = Path(__file__).resolve().parent / "_gliner2"

WHOLE_FILES = [
    "configuration.py",
    "processor.py",
    "inference/__init__.py",
    "inference/candidate_decoder.py",
    "inference/chunking.py",
    "inference/overlap.py",
    "inference/runtime.py",
    "inference/schema.py",
    "inference/schema_model.py",
    "processing/__init__.py",
    "processing/boundary_preprocessing.py",
    "processing/layouts.py",
    "processing/records.py",
    "processing/targets.py",
    "processing/word_splitter.py",
    "models/__init__.py",
    "models/base.py",
    "models/candidates.py",
    "models/outputs.py",
    "models/boundary/__init__.py",
    "models/boundary/constants.py",
    "models/boundary/engine.py",
    "models/boundary/relations.py",
    "models/boundary/validation.py",
    "training/__init__.py",
]
# model.py: inference helpers only; the rest is torch model classes.
MODEL_FUNCTIONS = ["_schema_group_name", "_group_scored_candidates"]
MODEL_METHODS = ["_encode_core", "_single_sample_candidates"]

HEADER = (
    "# Copied from gliner2 {version} ({path}), Apache-2.0,\n"
    "# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;\n"
    "# only import lines differ from upstream. Do not edit by hand.\n"
)

REWRITES = [
    (
        r"^(\s*)import torch\.nn\.functional as F\b",
        rf"\1from {PACKAGE}._tensor import functional as F",
    ),
    (r"^(\s*)import torch\.nn as nn\b", rf"\1from {PACKAGE}._tensor import nn"),
    (r"^(\s*)from torch import nn\b", rf"\1from {PACKAGE}._tensor import nn"),
    (
        r"^(\s*)from torch\.nn\.utils\.rnn import pad_sequence\b",
        rf"\1from {PACKAGE}._tensor import pad_sequence",
    ),
    (
        r"^(\s*)from torch\.utils\.data import DataLoader\b",
        rf"\1from {PACKAGE}._tensor import DataLoader",
    ),
    (r"^(\s*)import torch\b", rf"\1from {PACKAGE} import _tensor as torch"),
    (r"^(\s*)from transformers import\b", rf"\1from {PACKAGE}._hf import"),
    (r"^(\s*)from gliner2(\.| import)", rf"\1from {PACKAGE}._gliner2\2"),
    (r"^(\s*)import gliner2\b", rf"\1import {PACKAGE}._gliner2 as gliner2"),
]


def _rewrite(source: str) -> str:
    for pattern, replacement in REWRITES:
        source = re.sub(pattern, replacement, source, flags=re.MULTILINE)
    return source


def _extract_model_helpers(source: str) -> str:
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)

    def segment(node):
        start = min([node.lineno] + [d.lineno for d in getattr(node, "decorator_list", [])])
        return "".join(lines[start - 1 : node.end_lineno])

    imports = [
        segment(n)
        for n in tree.body
        if isinstance(n, (ast.Import, ast.ImportFrom))
        and not any(
            m in segment(n)
            for m in (
                "encoding import",
                "heads import",
                "pool import",
                "proposal import",
                "scoring import",
                "losses import",
                "records import",
                "targets_device import",
                "loading import",
                "layers import",
                "device_errors import",
                "processing.targets import",
                "rnn import",
            )
        )
    ]
    functions = [
        segment(n)
        for n in tree.body
        if isinstance(n, ast.FunctionDef) and n.name in MODEL_FUNCTIONS
    ]
    (cls,) = [
        n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "BoundaryExtractorModel"
    ]
    methods = [
        segment(n) for n in cls.body if isinstance(n, ast.FunctionDef) and n.name in MODEL_METHODS
    ]
    return (
        "".join(imports)
        + "\n\n"
        + "\n\n".join(functions)
        + "\n\nclass BoundaryExtractorModel(nn.Module):\n"
        + '    """Inference helpers of gliner2\'s BoundaryExtractorModel (the model itself runs on ONNX)."""\n\n'
        + "\n".join(methods)
    )


def vendor(OUT: Path = DEFAULT_OUT) -> Path:
    import gliner2

    src = Path(gliner2.__file__).resolve().parent
    gliner2_version = version("gliner2")
    for rel in WHOLE_FILES:
        target = OUT / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        # Package markers stay empty: upstream __init__ files re-export the torch
        # model classes, and every copied module imports its siblings by full path.
        text = "" if target.name == "__init__.py" else (src / rel).read_text()
        target.write_text(HEADER.format(version=gliner2_version, path=rel) + _rewrite(text))
    model = OUT / "models/boundary/model.py"
    model.write_text(
        HEADER.format(version=gliner2_version, path="models/boundary/model.py (inference helpers)")
        + _rewrite(_extract_model_helpers((src / "models/boundary/model.py").read_text()))
    )
    trainer_source = (src / "training/trainer.py").read_text()
    trainer_tree = ast.parse(trainer_source)
    trainer_lines = trainer_source.splitlines(keepends=True)
    (collator,) = [
        n
        for n in trainer_tree.body
        if isinstance(n, ast.ClassDef) and n.name == "ExtractorCollator"
    ]
    (OUT / "training/trainer.py").write_text(
        HEADER.format(version=gliner2_version, path="training/trainer.py (ExtractorCollator only)")
        + "from __future__ import annotations\n\nfrom typing import Dict, List, Optional, Tuple\n\n\n"
        + "".join(trainer_lines[collator.lineno - 1 : collator.end_lineno])
    )
    (OUT / "api_client.py").write_text(
        "# Not copied: gliner2's hosted-API client (network inference) is not a local path.\n\n\n"
        "class GLiNER2API:\n"
        "    def __init__(self, *args, **kwargs):\n"
        '        raise NotImplementedError("the torch-free GLiNER path is local-only")\n'
    )
    records = OUT / "models/boundary/records.py"
    records.write_text(
        "# Not copied: gliner2's record decoder is training-coupled and cognee's\n"
        "# entity + relation schema never decodes records.\n\n\n"
        "def decode_group(*args, **kwargs):\n"
        '    raise NotImplementedError("record extraction is not supported by the torch-free GLiNER path")\n'
    )
    (OUT / "__init__.py").write_text(
        HEADER.format(version=gliner2_version, path="(package)")
        + f'__version__ = "{gliner2_version}"\n'
    )
    return OUT


def main() -> None:
    out = vendor()
    print(f"vendored gliner2 {version('gliner2')} into {out}")


if __name__ == "__main__":
    main()
