apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognee.fullname" . }}
  labels:
    {{- include "cognee.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "cognee.selectorLabels" . | nindent 4 }}
