apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cognee.configMapName" . }}
  labels:
    {{- include "cognee.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  ENABLE_BACKEND_ACCESS_CONTROL: {{ .Values.cognee.backendAccessControl | quote }}
{{ range $key, $value := .Values.cognee.env -}}
  {{ $key }}: {{ $value | quote }}
{{ end }}
