apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognee.postgres.fullname" . }}
  labels:
    {{- include "cognee.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    {{- include "cognee.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
