apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cognee.postgres.fullname" . }}-pvc
  labels:
    {{- include "cognee.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
