{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cognee.fullname" . }}-secret
  labels:
    {{- include "cognee.labels" . | nindent 4 }}
type: Opaque
data:
  LLM_API_KEY: {{ "" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgres.auth.password | b64enc | quote }}
{{- end }}
