import { Flex } from "@mantine/core";
import ContentSectionWrapper from "./ContentSectionWrapper";
import TitleText from "./TitleText";
import Image from "next/image";

export default function TrustedByDevelopersSection() {
  return (
    <ContentSectionWrapper>
      <Flex className="flex-col">
        <TitleText>Trusted by developers:</TitleText>
        <Flex className="gap-[1.5rem] flex-wrap max-w-[33.8125rem]">
          <Image
            src={"/images/logos/redis-logo.png"}
            alt={"Redis"}
            width={98}
            height={32}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/bayer-logo.png"}
            alt={"Bayer"}
            width={52}
            height={52}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/atlassian-logo.png"}
            alt={"Atlassian"}
            width={160}
            height={20}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/aws-logo.png"}
            alt={"AWS"}
            width={58}
            height={36}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/splunk-logo.png"}
            alt={"Splunk"}
            width={114}
            height={34}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/autodesk-logo.png"}
            alt={"AutoDesk"}
            width={160}
            height={30}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/botpress-logo.png"}
            alt={"Botpress"}
            width={132}
            height={36}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/blended-logo.png"}
            alt={"Blended"}
            width={128}
            height={28}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/infosys-logo.png"}
            alt={"InfoSys"}
            width={78}
            height={32}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/ribbon-logo.png"}
            alt={"Ribbon"}
            width={110}
            height={34}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/reply-logo.png"}
            alt={"Ribbon"}
            width={100}
            height={26}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/studocu-logo.png"}
            alt={"Studocu"}
            width={138}
            height={34}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/kovai-logo.png"}
            alt={"Kovai.co"}
            width={102}
            height={28}
            objectFit="cover"
            className="object-contain"
          />
          <Image
            src={"/images/logos/rentpost-logo.png"}
            alt={"Rentpost"}
            width={134}
            height={28}
            objectFit="cover"
            className="object-contain"
          />
        </Flex>
      </Flex>
    </ContentSectionWrapper>
  );
}
