blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/NQtRemgQVD
    about: Join our Discord community for questions, discussions, and support
  - name: 📖 Documentation
    url: https://docs.cognee.ai
    about: Check our documentation for guides and API references
