"""loader_separation

Revision ID: 9e7a3cb85175
Revises: 1daae0df1866
Create Date: 2025-08-14 19:18:11.406907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e7a3cb85175"
down_revision: Union[str, None] = "1daae0df1866"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data", sa.Column("original_extension", sa.String(), nullable=True))
    op.add_column("data", sa.Column("original_mime_type", sa.String(), nullable=True))
    op.add_column("data", sa.Column("loader_engine", sa.String(), nullable=True))
    op.add_column("data", sa.Column("original_data_location", sa.String(), nullable=True))
    op.add_column("data", sa.Column("raw_content_hash", sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column("data", "raw_content_hash")
    op.drop_column("data", "original_data_location")
    op.drop_column("data", "loader_engine")
    op.drop_column("data", "original_mime_type")
    op.drop_column("data", "original_extension")
