"""Expand data model info

Revision ID: e4ebee1091e7
Revises: ab7e313804ae
Create Date: 2025-07-24 13:21:30.738486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4ebee1091e7"
down_revision: Union[str, None] = "ab7e313804ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_metadata")
    op.drop_table("_dlt_loads")
    op.drop_table("_dlt_version")
    op.drop_table("_dlt_pipeline_state")
    op.add_column("data", sa.Column("tenant_id", sa.UUID(), nullable=True))
    op.add_column("data", sa.Column("data_size", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_data_tenant_id"), "data", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_data_tenant_id"), table_name="data")
    op.drop_column("data", "data_size")
    op.drop_column("data", "tenant_id")
    op.create_table(
        "_dlt_pipeline_state",
        sa.Column("version", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("engine_version", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("pipeline_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("state", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("version_hash", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("_dlt_load_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("_dlt_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    )
    op.create_table(
        "_dlt_version",
        sa.Column("version", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("engine_version", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "inserted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("schema_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version_hash", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("schema", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.create_table(
        "_dlt_loads",
        sa.Column("load_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("schema_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "inserted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("schema_version_hash", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "file_metadata",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("extension", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("mime_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content_hash", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("_dlt_load_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("_dlt_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("node_set", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
