from enum import Enum


class SearchType(str, Enum):
    CHUNKS = "CHUNKS"
    CHUNKS_LEXICAL = "CHUNKS_LEXICAL"
    CODE = "CODE"
    CODING_RULES = "CODING_RULES"
    CYPHER = "CYPHER"
    FEEDBACK = "FEEDBACK"
    FEELING_LUCKY = "FEELING_LUCKY"
    GRAPH_COMPLETION = "GRAPH_COMPLETION"
    GRAPH_COMPLETION_CONTEXT_EXTENSION = "GRAPH_COMPLETION_CONTEXT_EXTENSION"
    GRAPH_COMPLETION_COT = "GRAPH_COMPLETION_COT"
    GRAPH_SUMMARY_COMPLETION = "GRAPH_SUMMARY_COMPLETION"
    INSIGHTS = "INSIGHTS"
    NATURAL_LANGUAGE = "NATURAL_LANGUAGE"
    RAG_COMPLETION = "RAG_COMPLETION"
    SUMMARIES = "SUMMARIES"
    TEMPORAL = "TEMPORAL"

    def __str__(self) -> str:
        return str(self.value)
