# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {
    "types.Edge": types.Edge,
    "stream_types.Edge": stream_types.Edge,
    "types.KnowledgeGraph": types.KnowledgeGraph,
    "stream_types.KnowledgeGraph": stream_types.KnowledgeGraph,
    "types.Node": types.Node,
    "stream_types.Node": stream_types.Node,
    "types.SummarizedClass": types.SummarizedClass,
    "stream_types.SummarizedClass": stream_types.SummarizedClass,
    "types.SummarizedCode": types.SummarizedCode,
    "stream_types.SummarizedCode": stream_types.SummarizedCode,
    "types.SummarizedContent": types.SummarizedContent,
    "stream_types.SummarizedContent": stream_types.SummarizedContent,
    "types.SummarizedFunction": types.SummarizedFunction,
    "stream_types.SummarizedFunction": stream_types.SummarizedFunction,
}
