"""LLM Interface"""

from abc import ABC, abstractmethod
from typing import Any, TypeVar

import litellm
from pydantic import BaseModel

from cognee.infrastructure.llm.structured_output_framework.litellm_instructor.llm.types import (
    TranscriptionReturnType,
)

T = TypeVar("T", bound="BaseModel | str")


class LLMInterface(ABC):
    """
    Define an interface for LLM models with methods for structured output, multimodal processing, and prompt display.

    Methods:
    - acreate_structured_output(text_input: str, system_prompt: str, response_model: Type[BaseModel])
    """

    max_completion_tokens: int

    # Whether a plain-text answer from this adapter reaches a listening
    # TokenSink. Declared rather than inferred because "will not stream" and
    # "has not streamed yet" are indistinguishable at the promotion site, and
    # guessing wrong means announcing a stream that never produces a token.
    # Default False: an adapter opts in by routing through stream_text_completion.
    supports_answer_streaming: bool = False

    @abstractmethod
    async def acreate_structured_output(
        self, text_input: str, system_prompt: str, response_model: type[T]
    ) -> T:
        """
        Obtain structured output from text input using a specified response model.

        This function must be implemented by subclasses to provide the actual functionality for
        generating structured output. Raises NotImplementedError if not implemented.

        Parameters:
        -----------

            - text_input (str): Input text from the user to be processed.
            - system_prompt (str): The system prompt that guides the model's response.
            - response_model (Type[BaseModel]): The model type that will structure the response
              output.
        """
        raise NotImplementedError

    @abstractmethod
    async def create_transcript(self, input: str, **kwargs: Any) -> TranscriptionReturnType | None:
        """
        Generate an audio transcript from a user query.

        This method creates a transcript from the specified audio file, raising a
        FileNotFoundError if the file does not exist. The audio file is processed and the
        transcription is retrieved from the API.

        Parameters:
        -----------
            - input: The path to the audio file that needs to be transcribed.
            - kwargs: Optional provider-specific transcription options (e.g. response
              format or timestamp granularities). Implementations that do not support
              them should accept and ignore them rather than raise.

        Returns:
        --------
            The generated transcription of the audio file.
        """
        ...

    # TODO: Implement a return type. Most adapters return a 'ModelResponse' while the Ollama adapter does something else.
    @abstractmethod
    async def transcribe_image(
        self,
        input: str,
        prompt: str | None = None,
        max_completion_tokens: int | None = None,
        reasoning_effort: str | None = None,
    ) -> Any:
        """
        Generate a transcription of an image from a user query.

        This method encodes the image and sends a request to the API to obtain a
        description of the contents of the image.

        Parameters:
        -----------
            - input: The path to the image file that needs to be transcribed.
            - prompt: Optional extraction instruction; adapter default when omitted.
            - max_completion_tokens: Optional length cap; adapter default when omitted.
            - reasoning_effort: Optional reasoning-effort hint for reasoning models; ignored on
              models that do not support it.

        Returns:
        --------
            - ModelResponse: A structured output generated by the model, returned as an instance of
              BaseModel.
        """
        ...
