"""Universal label bank for schema selection.

~120 pre-named, pre-described entity types drawn from common NER taxonomies
(FewNERD / OntoNotes style) plus technical, medical, legal, and scientific
additions. Schema discovery probes the data with these candidates and keeps
the ones that fire — selection instead of invention: names and descriptions
are hand-quality (GLiNER's precision depends on descriptions), results are
deterministic, and type names stay consistent across datasets.
"""

LABEL_BANK = {
    # people and roles
    "person": "Named individual people",
    "politician": "Politicians, heads of state, government officials",
    "scientist": "Scientists, researchers, academics",
    "artist": "Artists, musicians, actors, writers, performers",
    "athlete": "Athletes and sports players",
    "military_officer": "Military commanders, officers, and soldiers",
    "healthcare_professional": "Doctors, nurses, surgeons, medical staff",
    "executive": "Business executives, founders, managers",
    "engineer": "Engineers and technical professionals",
    "lawyer": "Lawyers, judges, legal professionals",
    "patient": "Patients or people receiving medical care",
    "journalist": "Journalists, reporters, editors",
    "astronaut": "Astronauts and space crew members",
    "fictional_character": "Fictional or mythological characters",
    # organizations
    "company": "Companies, corporations, businesses",
    "government_agency": "Government agencies, ministries, public bodies",
    "military_unit": "Armies, regiments, fleets, military units",
    "political_party": "Political parties and movements",
    "educational_institution": "Universities, schools, colleges",
    "hospital": "Hospitals, clinics, medical facilities",
    "sports_team": "Sports teams and clubs",
    "research_institution": "Research institutes, laboratories",
    "financial_institution": "Banks, funds, exchanges, insurers",
    "media_outlet": "Newspapers, broadcasters, media organizations",
    "nonprofit": "Nonprofits, NGOs, charities, foundations",
    "religious_organization": "Churches, religious bodies and orders",
    # places
    "city": "Cities, towns, villages",
    "country": "Countries and sovereign states",
    "region": "Regions, states, provinces, geographic areas",
    "building": "Named buildings, venues, landmarks",
    "facility": "Industrial or operational facilities, plants, bases",
    "road": "Roads, streets, highways",
    "river": "Rivers, lakes, seas, bodies of water",
    "mountain": "Mountains, ranges, peaks",
    "island": "Islands and archipelagos",
    "airport": "Airports and transit hubs",
    "address": "Street addresses and postal locations",
    "celestial_body": "Planets, moons, stars, asteroids, comets",
    # time
    "date": "Calendar dates and years",
    "time": "Times of day",
    "duration": "Durations and time spans",
    "era": "Historical periods, eras, ages",
    # quantities
    "money": "Monetary amounts with currency",
    "percentage": "Percentages and rates",
    "measurement": "Physical measurements with units",
    "dosage": "Medication dosages like 5mg or two tablets",
    "distance": "Distances and lengths",
    "temperature": "Temperatures",
    "quantity": "Counts and amounts of things",
    # creative works
    "book": "Books, novels, written works",
    "film": "Films, movies, TV shows",
    "song": "Songs, albums, musical works",
    "artwork": "Paintings, sculptures, artworks",
    "publication": "Papers, articles, reports, journals",
    "video_game": "Video games",
    # products and technology
    "product": "Commercial products and models",
    "vehicle": "Cars, ships, aircraft, trains",
    "spacecraft": "Spacecraft, space capsules, space stations",
    "rocket": "Rockets and launch vehicles",
    "weapon": "Weapons and weapon systems",
    "device": "Electronic devices and hardware",
    "machine": "Machines and mechanical equipment",
    "material": "Materials and substances used in construction or manufacture",
    "chemical_substance": "Chemicals, compounds, fuels, elements",
    "food": "Foods, dishes, beverages",
    "software": "Software products and applications",
    "programming_language": "Programming languages",
    "database": "Database systems and data stores",
    "framework": "Software frameworks and libraries",
    "algorithm": "Algorithms and computational methods",
    "ai_model": "Machine learning models and AI systems",
    "protocol": "Network or communication protocols and standards",
    "website": "Websites and online platforms",
    "dataset": "Named datasets and corpora",
    "file_format": "File formats and data formats",
    # medical
    "disease": "Diseases, disorders, medical conditions",
    "symptom": "Symptoms and clinical findings",
    "medication": "Drugs, medications, pharmaceutical substances",
    "medical_procedure": "Medical procedures, surgeries, therapies",
    "anatomical_structure": "Organs, tissues, body parts",
    "medical_device": "Medical devices and instruments",
    "pathogen": "Viruses, bacteria, pathogens",
    "gene": "Genes and genetic variants",
    "protein": "Proteins and enzymes",
    # legal and business
    "law": "Laws, statutes, acts, treaties",
    "regulation": "Regulations, directives, policies",
    "contract": "Contracts, agreements, deals",
    "court_case": "Court cases and legal proceedings",
    "patent": "Patents and intellectual property",
    "financial_instrument": "Stocks, bonds, derivatives, securities",
    "currency": "Currencies including cryptocurrencies",
    "tax": "Taxes, tariffs, duties",
    "license": "Licenses and permits",
    # events
    "event": "Named events and occurrences",
    "war": "Wars and armed conflicts",
    "battle": "Battles and military engagements",
    "election": "Elections and referendums",
    "conference": "Conferences, summits, meetings",
    "disaster": "Natural disasters and accidents",
    "sports_event": "Sports events, matches, tournaments",
    "space_mission": "Space missions and launches",
    "holiday": "Holidays and observances",
    # science
    "species": "Animal, plant, and microbial species",
    "chemical_element": "Chemical elements",
    "mineral": "Minerals and ores",
    "theory": "Scientific theories, laws, principles",
    "experiment": "Named experiments and studies",
    "unit_of_measure": "Units of measurement",
    # misc
    "language": "Human languages and dialects",
    "nationality": "Nationalities and ethnic groups",
    "religion": "Religions and belief systems",
    "award": "Awards, prizes, honors",
    "title": "Titles, ranks, honorifics",
    "industry": "Industries and economic sectors",
    "project": "Named projects, programs, initiatives",
    "standard": "Technical or industry standards",
    "skill": "Skills, competencies, disciplines",
}

RELATION_BANK = {
    # generic / structural
    "part_of": "Membership or composition: one entity is a component of another",
    "member_of": "A person or entity belongs to a group or organization",
    "located_in": "Geographic relationship: entity is in a place",
    "works_for": "Employment or service: person works at an organization",
    "founded": "A person or organization created an organization",
    "created": "An entity made a product, work, or system",
    "owns": "Ownership of an asset, company, or object",
    "uses": "An entity uses a tool, technology, or material",
    "named_after": "An entity is named after a person or thing",
    "based_on": "A work or system derives from another",
    # business
    "acquired": "One company bought another company or asset",
    "partnered_with": "Two organizations collaborate or form a partnership",
    "invested_in": "An investor put money into a company or project",
    "awarded_to": "A contract, prize, or grant given to a recipient",
    "contracted_by": "An entity performs work under contract for another",
    "supplies": "One entity provides components or services to another",
    "manufactured_by": "A product is made by a company",
    "funded_by": "An entity receives funding from another",
    "led_by": "An organization, team, or program is led by a person",
    "subsidiary_of": "A company is owned by a parent company",
    "competes_with": "Two entities compete in a market or contest",
    # events and time
    "scheduled_for": "An event or mission is planned for a date",
    "occurred_on": "An event happened on a date or at a time",
    "participated_in": "A person or group took part in an event",
    "caused": "One event or entity caused another event or condition",
    # military / historical
    "commands": "A person leads a military unit or force",
    "fought_in": "A person or army took part in a battle or war",
    "defeated": "One side beat another in battle, war, or contest",
    "allied_with": "Two parties formed an alliance",
    # people
    "married_to": "Marriage relationship between two people",
    "relative_of": "Family relationship between two people",
    "advisor_to": "A person advises another person or organization",
    "succeeded": "A person or entity followed another in a role",
    "born_in": "A person was born in a place or year",
    "educated_at": "A person studied at an institution",
    # technology / science / space
    "powered_by": "A machine or vehicle is driven by an engine or fuel",
    "developed_by": "A technology or product was developed by an entity",
    "runs_on": "Software runs on a platform or infrastructure",
    "integrates_with": "One system connects to or works with another",
    "launched_from": "A vehicle or mission launched from a site",
    "orbits": "A body or spacecraft orbits a celestial body",
    "discovered": "A person or team discovered something",
    # medical
    "treats": "A drug, procedure, or practitioner treats a condition",
    "prescribed_by": "A medication was prescribed by a practitioner",
    "diagnosed_with": "A patient has a diagnosed condition",
    "administered_to": "A drug or treatment was given to a patient",
    "symptom_of": "A finding is a symptom of a condition",
}

# Broad seeds used for residue detection: spans these catch that no selected
# bank label covers are evidence of a type the bank is missing.
GENERIC_SEEDS = {
    "person": "Any named individual",
    "organization": "Any organization or group",
    "location": "Any place or location",
    "object": "Any physical object or artifact",
    "substance": "Any material or substance",
    "activity": "Any activity, process, or action",
    "event": "Any named event",
    "quantity": "Any number, amount, or measurement",
}
