"use client";

import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { useCogniInstance } from "@/modules/tenant/TenantProvider";
import confirmSlackLink from "@/modules/integrations/slack/confirmSlackLink";

export default function LinkSlackPage() {
  const { cogniInstance, localInstance } = useCogniInstance();
  const instance = cogniInstance || localInstance;
  const searchParams = useSearchParams();
  const code = searchParams.get("code") || "";

  const [state, setState] = useState<"idle" | "linking" | "done" | "error">("idle");
  const [error, setError] = useState<string | null>(null);

  async function handleConfirm() {
    if (!instance || !code) return;
    setState("linking");
    setError(null);
    try {
      await confirmSlackLink(instance, code);
      setState("done");
    } catch (err) {
      const detail =
        err && typeof err === "object" && ("detail" in err || "message" in err)
          ? String((err as { detail?: string; message?: string }).detail || (err as { message?: string }).message)
          : "Could not link your account. Please try again.";
      setError(detail);
      setState("error");
    }
  }

  return (
    <div style={{ maxWidth: 440, margin: "80px auto", padding: 24, display: "flex", flexDirection: "column", gap: 16 }}>
      <div
        style={{
          background: "rgba(255,255,255,0.06)",
          backdropFilter: "blur(12px)",
          border: "1px solid rgba(255,255,255,0.1)",
          borderRadius: 12,
          padding: 24,
          display: "flex",
          flexDirection: "column",
          gap: 12,
        }}
      >
        <h1 style={{ fontSize: 18, fontWeight: 700, color: "#EDECEA", margin: 0 }}>Link your Slack account</h1>

        {!code && (
          <p style={{ fontSize: 13, color: "rgba(237,236,234,0.55)", margin: 0 }}>
            This page needs a link generated by running <code>/cognee-link</code> in Slack — open
            the link from that message instead of coming here directly.
          </p>
        )}

        {code && state !== "done" && (
          <>
            <p style={{ fontSize: 13, color: "rgba(237,236,234,0.55)", margin: 0 }}>
              Confirm as <strong style={{ color: "#EDECEA" }}>this account</strong> to make
              <code> /cognee-ask</code> and &quot;Remember this&quot; use your own Cognee memory
              from Slack, instead of the workspace installer&apos;s.
            </p>
            {error && <p style={{ fontSize: 12, color: "#F87171", margin: 0 }}>{error}</p>}
            <button
              onClick={handleConfirm}
              disabled={state === "linking" || !instance}
              style={{
                alignSelf: "flex-start",
                background: "#6510F4",
                color: "#fff",
                border: "none",
                borderRadius: 8,
                padding: "8px 18px",
                fontSize: 13,
                fontWeight: 500,
                cursor: state === "linking" || !instance ? "wait" : "pointer",
              }}
            >
              {state === "linking" ? "Linking…" : "Confirm"}
            </button>
          </>
        )}

        {state === "done" && (
          <p style={{ fontSize: 13, color: "#4ADE80", margin: 0 }}>
            Linked! You can close this tab and go back to Slack.
          </p>
        )}
      </div>
    </div>
  );
}
