name: cognee-setup
description: "Sets up Python, installs uv, and installs dependencies for Cognee."

inputs:
  python-version:
    description: "Which Python version to use"
    required: false
    default: "3.11.x"

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: uv sync --extra api --extra docs --extra evals --extra gemini --extra codegraph --extra ollama --extra dev --extra neo4j
