name: 'Build Docker images for Cognee'
description: 'Build cognee-related Docker images and push to the Docker registry (AWS ECR)'
inputs:
  stage:
    description: 'The stage of the pipeline, such as "dev" or "prd", for the Cognee app'
    required: true
  aws_account_id:
    description: 'The AWS account ID for the Cognee app'
    required: true
  should_publish:
    description: 'Whether to publish the Cognee Docker image to AWS ECR; should be either "true" or "false"'
    required: true
  ecr_image_repo_name:
    description: 'The Docker image ECR repository name for the Cognee app, such as "workflows"'
    required: true
  dockerfile_location:
    description: 'The  directory location of the Dockerfile for the Cognee app'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build PromethAI App Docker image
      shell: bash
      env:
        STAGE: ${{ inputs.stage }}
      run: |
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        push: ${{ env.PUSH_FLAG }}
        tags: ${{ env.IMAGE_TAGS }}
        labels: ${{ env.IMAGE_LABELS }}
      env:
        DOCKERFILE_PATH: ${{ inputs.dockerfile }}
        PUSH_FLAG: ${{ github.event_name != 'pull_request' }}
        IMAGE_TAGS: ${{ steps.meta.outputs.tags }}
        IMAGE_LABELS: ${{ steps.meta.outputs.labels }}
