name: 'Image Builder'
description: 'Build and push Docker images'
inputs:
  registry:
    description: 'Container registry'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password'
    required: true
  image_name:
    description: 'Image name'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  context:
    description: 'Build context'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Build and push Docker image
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        IMAGE_NAME: ${{ inputs.image_name }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        CONTEXT: ${{ inputs.context }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        echo "Building Docker image..."
        echo "$PASSWORD" | docker login "$REGISTRY" -u "$USERNAME" --password-stdin
        
        # Build the image with proper tags
        if [ "$GITHUB_REF_NAME" = "main" ] || [ "$GITHUB_REF_NAME" = "master" ]; then
          TAG="latest"
        else
          TAG="$GITHUB_REF_NAME"
        fi
        
        docker build -f "$DOCKERFILE" -t "$REGISTRY/$IMAGE_NAME:$TAG" -t "$REGISTRY/$IMAGE_NAME:$GITHUB_SHA" "$CONTEXT"
        docker push "$REGISTRY/$IMAGE_NAME:$TAG"
        docker push "$REGISTRY/$IMAGE_NAME:$GITHUB_SHA"
        
        echo "Image pushed successfully!"
