# Copied from gliner2 2.0.0 (processing/layouts.py), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
"""Build architecture-neutral query layouts from schemas and explicit spans.

A ``QueryLayout`` enumerates the extractive and classification queries of a
sample. This module constructs one from the existing schema dict form (the
same shape ``SchemaTransformer`` consumes) so both architectures can share a
single query addressing scheme.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List, Mapping, Optional

from cognee.tasks.graph.gliner_demo.onnx._gliner2.models.base import QueryLayout, QuerySpec
from cognee.tasks.graph.gliner_demo.onnx._gliner2.processing.targets import TargetGraph


@dataclass(frozen=True)
class SpanAnnotation:
    """Explicit-offset span annotation. Offsets index the original text."""
    label: str
    start: int
    end: int
    text: Optional[str] = None

    def __post_init__(self) -> None:
        if self.end <= self.start:
            raise ValueError(
                f"SpanAnnotation requires end > start, got [{self.start}, {self.end})"
            )


def build_query_layout(schema: Mapping[str, Any]) -> QueryLayout:
    """Build a :class:`QueryLayout` from a schema dict.

    Supported keys:
      * ``entities``: mapping ``label -> ...`` → one extractive query per label.
      * ``classifications``: list of ``{"task": name, "labels": [...]}`` →
        one classification query per task.
      * ``json_structures``: list of ``{parent: {field: ...}}`` → one
        extractive query per (parent, field).

    Query ids are assigned in a stable order: entities, then json-structure
    fields, then classifications.
    """
    queries: List[QuerySpec] = []
    qid = 0
    task_index = 0

    entities = schema.get("entities") or {}
    if entities:
        for role_index, label in enumerate(entities.keys()):
            queries.append(
                QuerySpec(
                    query_id=qid,
                    task_index=task_index,
                    task_type="entities",
                    task_name="entities",
                    role_index=role_index,
                    role_name=str(label),
                    field_path=(str(label),),
                    extractive=True,
                )
            )
            qid += 1
        task_index += 1

    for struct in schema.get("json_structures", []) or []:
        for parent, fields in struct.items():
            for role_index, fname in enumerate(fields.keys()):
                queries.append(
                    QuerySpec(
                        query_id=qid,
                        task_index=task_index,
                        task_type="json_structures",
                        task_name=str(parent),
                        role_index=role_index,
                        role_name=str(fname),
                        field_path=(str(parent), str(fname)),
                        extractive=True,
                    )
                )
                qid += 1
            task_index += 1

    for item in schema.get("classifications", []) or []:
        name = str(item.get("task", f"classification_{task_index}"))
        queries.append(
            QuerySpec(
                query_id=qid,
                task_index=task_index,
                task_type="classifications",
                task_name=name,
                role_index=0,
                role_name=name,
                field_path=(name,),
                extractive=False,
            )
        )
        qid += 1
        task_index += 1

    return QueryLayout(queries=tuple(queries))


def validate_target_graph(
    graph: TargetGraph,
    query_layout: QueryLayout,
    text_length: int,
) -> None:
    """Validate a target graph against a query layout and text length."""
    valid_ids = {query.query_id for query in query_layout.queries}
    for mention in graph.mentions:
        if mention.query_id not in valid_ids:
            raise ValueError(
                f"mention references unknown query_id {mention.query_id}; "
                f"valid ids: {sorted(valid_ids)}"
            )
        if not (0 <= mention.start < mention.end <= text_length):
            raise ValueError(
                f"mention [{mention.start}, {mention.end}) invalid for text_length {text_length}"
            )
    for choice in graph.choices:
        if choice.query_id not in valid_ids:
            raise ValueError(f"choice references unknown query_id {choice.query_id}")
    for edge in graph.edges:
        if edge.query_id not in valid_ids:
            raise ValueError(f"edge references unknown query_id {edge.query_id}")

    seen_instance_ids = set()
    for record in graph.records:
        if record.instance_id in seen_instance_ids:
            raise ValueError(f"duplicate record instance_id {record.instance_id!r}")
        seen_instance_ids.add(record.instance_id)
        if record.anchor_query_id is not None and record.anchor_query_id not in valid_ids:
            raise ValueError(
                f"record {record.instance_id!r} anchor references unknown "
                f"query_id {record.anchor_query_id}"
            )
        for field_target in record.fields:
            if field_target.query_id not in valid_ids:
                raise ValueError(
                    f"record {record.instance_id!r} field references unknown "
                    f"query_id {field_target.query_id}"
                )
            for value in field_target.values:
                for start, end in value:
                    if not (0 <= start < end <= text_length):
                        raise ValueError(
                            f"record {record.instance_id!r} field {field_target.query_id} span "
                            f"[{start}, {end}) invalid for text_length {text_length}"
                        )
