# Copied from gliner2 2.0.0 (processing/targets.py), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
"""Canonical, architecture-neutral training targets and coordinate utilities.

All span coordinates are half-open ``[start, end)`` token boundaries. Character
offsets index the *original* (unmutated) text. These structures are consumed by
the boundary model and by target validation; they never silently drop or
truncate gold annotations.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, List, Mapping, Optional, Sequence, Tuple

from cognee.tasks.graph.gliner_demo.onnx import _tensor as torch

logger = logging.getLogger(__name__)

# Valid values for the gold-capacity overflow policy.
CAPACITY_POLICIES = ("raise", "truncate_with_warning", "skip_sample")


class TargetCapacityError(ValueError):
    """Raised when unique gold targets exceed the configured capacity."""


# =============================================================================
# Canonical target classes
# =============================================================================

@dataclass(frozen=True)
class MentionTarget:
    query_id: int
    start: int
    end: int
    annotation_id: Optional[str] = None

    def __post_init__(self) -> None:
        if self.end <= self.start:
            raise ValueError(
                f"MentionTarget requires half-open end > start, got [{self.start}, {self.end})"
            )


@dataclass(frozen=True)
class ChoiceTarget:
    query_id: int
    selected_choice_ids: Tuple[int, ...]


@dataclass(frozen=True)
class InstanceTarget:
    instance_id: str
    schema_node_id: int
    anchor_annotation_id: Optional[str] = None


@dataclass(frozen=True)
class EdgeTarget:
    query_id: int
    source_id: str
    target_id: str


@dataclass(frozen=True)
class LiteralTarget:
    target_id: str
    value: Any


# -- Record / instance identity targets --------------------------------------

@dataclass(frozen=True)
class RecordFieldTarget:
    """Gold values that fill one field of one record instance.

    ``values`` is a tuple of *distinct gold values*; each value is itself a tuple
    of alternative half-open ``(start, end)`` spans (occurrence alternatives).
    Scalar fields hold at most one value; list fields may hold several. An empty
    ``values`` tuple means the field is absent for this instance.
    """

    query_id: int
    values: Tuple[Tuple[Tuple[int, int], ...], ...] = ()


@dataclass(frozen=True)
class RecordTarget:
    """One gold record/event instance with stable identity and field bindings."""

    instance_id: str
    task_index: int
    fields: Tuple[RecordFieldTarget, ...] = ()
    anchor_query_id: Optional[int] = None

    def field_for_query(self, query_id: int) -> Optional[RecordFieldTarget]:
        for f in self.fields:
            if f.query_id == query_id:
                return f
        return None


@dataclass(frozen=True)
class TargetGraph:
    mentions: Tuple[MentionTarget, ...] = ()
    choices: Tuple[ChoiceTarget, ...] = ()
    instances: Tuple[InstanceTarget, ...] = ()
    edges: Tuple[EdgeTarget, ...] = ()
    literals: Tuple[LiteralTarget, ...] = ()
    records: Tuple[RecordTarget, ...] = ()

    def mentions_for_query(self, query_id: int) -> Tuple[MentionTarget, ...]:
        return tuple(m for m in self.mentions if m.query_id == query_id)

    def records_for_task(self, task_index: int) -> Tuple[RecordTarget, ...]:
        return tuple(r for r in self.records if r.task_index == task_index)


# =============================================================================
# Coordinate conversions
# =============================================================================

def inclusive_tokens_to_boundary_pair(start: int, end_inclusive: int) -> Tuple[int, int]:
    """``(start, end_inclusive) -> (start, end_inclusive + 1)`` (half-open)."""
    return start, end_inclusive + 1


def char_span_to_word_boundaries(
    char_start: int,
    char_end: int,
    start_mappings: Sequence[int],
    end_mappings: Sequence[int],
) -> Tuple[int, int]:
    """Convert a character span to half-open word-token boundaries.

    ``start_mappings[i]`` is the character start of word token ``i`` and
    ``end_mappings[i]`` is its exclusive character end. Returns
    ``(token_start, token_end)`` half-open such that the covered tokens are
    ``[token_start, token_end)``.

    Raises:
        ValueError: if the character span does not align to any token, or is
            empty/inverted.
    """
    if char_end <= char_start:
        raise ValueError(f"empty/inverted char span [{char_start}, {char_end})")
    n = len(start_mappings)
    if n == 0 or len(end_mappings) != n:
        raise ValueError("invalid token offset mappings")

    token_start = None
    for i in range(n):
        if start_mappings[i] <= char_start < end_mappings[i] or start_mappings[i] == char_start:
            token_start = i
            break
        if start_mappings[i] > char_start:
            token_start = i
            break
    if token_start is None:
        raise ValueError(f"char_start {char_start} does not map into any token")

    token_end_inclusive = None
    for i in range(n - 1, -1, -1):
        if start_mappings[i] < char_end <= end_mappings[i] or end_mappings[i] == char_end:
            token_end_inclusive = i
            break
        if end_mappings[i] < char_end:
            token_end_inclusive = i
            break
    if token_end_inclusive is None or token_end_inclusive < token_start:
        raise ValueError(f"char_end {char_end} does not map to a token >= start")

    return token_start, token_end_inclusive + 1


def word_boundaries_to_char_span(
    token_start: int,
    token_end: int,
    start_mappings: Sequence[int],
    end_mappings: Sequence[int],
) -> Tuple[int, int]:
    """Inverse of :func:`char_span_to_word_boundaries` for half-open boundaries.

    ``char_start = start_mappings[token_start]``,
    ``char_end = end_mappings[token_end - 1]``.
    """
    if token_end <= token_start:
        raise ValueError(f"empty/inverted token span [{token_start}, {token_end})")
    if token_start < 0 or token_end > len(end_mappings):
        raise ValueError("token boundaries out of range")
    return int(start_mappings[token_start]), int(end_mappings[token_end - 1])


# =============================================================================
# Surface occurrence resolution
# =============================================================================

def normalize_surface_occurrences(
    matches: Sequence[Tuple[int, int]],
    *,
    occurrence_policy: str,
    query_id: int = -1,
    surface: str = "",
) -> List[Tuple[int, int]]:
    """Resolve repeated surface matches per an explicit occurrence policy.

    ``matches`` are half-open ``(start, end)`` token spans. Policies:
      * ``"all"``    - keep every occurrence.
      * ``"first"``  - keep only the first occurrence.
      * ``"error_on_ambiguous"`` - raise if more than one occurrence exists.
    """
    if occurrence_policy not in ("all", "first", "error_on_ambiguous"):
        raise ValueError(f"unknown occurrence_policy {occurrence_policy!r}")
    if not matches:
        return []
    if occurrence_policy == "all":
        return list(matches)
    if occurrence_policy == "first":
        return [matches[0]]
    # error_on_ambiguous
    if len(matches) > 1:
        raise ValueError(
            f"ambiguous surface match: query_id={query_id} surface={surface!r} "
            f"has {len(matches)} occurrences; provide explicit offsets or use "
            "occurrence_policy='all'/'first'."
        )
    return [matches[0]]


# =============================================================================
# Dense per-query targets
# =============================================================================

def build_boundary_targets(
    graph: TargetGraph,
    query_count: int,
    text_length: int,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Build dense start/end/inside targets from a target graph.

    Returns ``(start_targets, end_targets, inside_targets)`` with shapes
    ``[Q, L + 1]``, ``[Q, L + 1]``, ``[Q, L]`` respectively. Start and end are
    multi-label (nested spans can share a boundary). Inside marks tokens covered
    by at least one mention of that query.
    """
    start = torch.zeros(query_count, text_length + 1)
    end = torch.zeros(query_count, text_length + 1)
    inside = torch.zeros(query_count, text_length)
    for m in graph.mentions:
        if not (0 <= m.query_id < query_count):
            raise ValueError(f"mention query_id {m.query_id} out of range")
        if not (0 <= m.start < m.end <= text_length):
            raise ValueError(
                f"mention [{m.start}, {m.end}) out of range for text_length {text_length}"
            )
        start[m.query_id, m.start] = 1.0
        end[m.query_id, m.end] = 1.0
        inside[m.query_id, m.start:m.end] = 1.0
    return start, end, inside


# =============================================================================
# Padded target batch
# =============================================================================

@dataclass
class PaddedTargetBatch:
    """Padded gold targets for a batch.

    Shapes (``B`` samples, ``Q`` queries, ``G`` max gold per query):
        mention_pairs:         [B, Q, G, 2]  half-open [start, end)
        mention_mask:          [B, Q, G]
        start_targets:         [B, Q, L + 1]
        end_targets:           [B, Q, L + 1]
        inside_targets:        [B, Q, L] or None
        classification_targets:[B, Q_c] or None
    """
    mention_pairs: torch.LongTensor
    mention_mask: torch.BoolTensor
    start_targets: Optional[torch.Tensor]
    end_targets: Optional[torch.Tensor]
    inside_targets: Optional[torch.Tensor] = None
    classification_targets: Optional[torch.Tensor] = None
    instance_targets: Any = None
    edge_targets: Any = None
    # Collator-built dense record spans:
    # (spans [B,R,N,F,S,2], span_mask [B,R,N,F,S],
    #  record_mask [B,R,N]).
    record_targets: Any = None
    # Per-sample record instance targets: List[List[RecordTarget]] or None.
    # Kept as opaque Python objects (span-based, device-independent) so the
    # record loss can map gold spans to per-sample candidate indices.
    records: Any = None

    def to(self, device) -> "PaddedTargetBatch":
        def mv(t):
            return t.to(device) if t is not None else None
        edge_targets = self.edge_targets
        if isinstance(edge_targets, tuple):
            edge_targets = tuple(mv(t) for t in edge_targets)
        record_targets = self.record_targets
        if isinstance(record_targets, tuple):
            record_targets = tuple(mv(t) for t in record_targets)
        return PaddedTargetBatch(
            mention_pairs=self.mention_pairs.to(device),
            mention_mask=self.mention_mask.to(device),
            start_targets=mv(self.start_targets),
            end_targets=mv(self.end_targets),
            inside_targets=mv(self.inside_targets),
            classification_targets=mv(self.classification_targets),
            instance_targets=self.instance_targets,
            edge_targets=edge_targets,
            record_targets=record_targets,
            records=self.records,
        )

    def pin_memory(self) -> "PaddedTargetBatch":
        def pin(t):
            return t.pin_memory() if t is not None else None
        edge_targets = self.edge_targets
        if isinstance(edge_targets, tuple):
            edge_targets = tuple(pin(t) for t in edge_targets)
        record_targets = self.record_targets
        if isinstance(record_targets, tuple):
            record_targets = tuple(pin(t) for t in record_targets)
        return PaddedTargetBatch(
            mention_pairs=self.mention_pairs.pin_memory(),
            mention_mask=self.mention_mask.pin_memory(),
            start_targets=pin(self.start_targets),
            end_targets=pin(self.end_targets),
            inside_targets=pin(self.inside_targets),
            classification_targets=pin(self.classification_targets),
            instance_targets=self.instance_targets,
            edge_targets=edge_targets,
            record_targets=record_targets,
            records=self.records,
        )


def pad_target_graphs(
    graphs: Sequence[TargetGraph],
    query_counts: Sequence[int],
    text_lengths: Sequence[int],
    max_gold_per_query: Optional[int],
    *,
    device: Optional[torch.device] = None,
    on_capacity_exceeded: str = "raise",
    build_dense: bool = True,
) -> PaddedTargetBatch:
    """Pad a list of target graphs into a ``PaddedTargetBatch``.

    Every unique gold mention is retained. If any (sample, query) has more
    unique mentions than ``max_gold_per_query`` the behavior is governed by
    ``on_capacity_exceeded``:

    * ``"raise"`` (default): raise :class:`TargetCapacityError` — gold is never
      silently truncated (the default preserves the no-silent-loss contract).
    * ``"truncate_with_warning"``: keep the first ``max_gold_per_query`` unique
      pairs for the offending query and log a warning with explicit counts.
    * ``"skip_sample"``: drop *all* gold for the offending sample (its targets
      become empty) and log a warning; the sample still occupies its batch slot
      but contributes no extraction supervision.

    ``device`` allocates the padded tensors directly on the given device
    (defense in depth so a fallback target path cannot leave CPU tensors to
    meet accelerator logits downstream).
    """
    if on_capacity_exceeded not in CAPACITY_POLICIES:
        raise ValueError(
            f"on_capacity_exceeded must be one of {CAPACITY_POLICIES}, "
            f"got {on_capacity_exceeded!r}"
        )
    b = len(graphs)
    if not (len(query_counts) == b and len(text_lengths) == b):
        raise ValueError("graphs, query_counts, text_lengths must be equal length")
    q = max(query_counts) if query_counts else 0
    l = max(text_lengths) if text_lengths else 0
    # Validate and group before allocating.  ``None`` is the allocation-safe
    # preflight mode: pad only to the largest count observed in this batch
    # instead of manufacturing an enormous artificial capacity.
    grouped_mentions: list[dict[int, list[tuple[int, int]]]] = []
    observed_max = 0
    for bi, (graph, qc, tl) in enumerate(zip(graphs, query_counts, text_lengths)):
        per_query: dict[int, list[tuple[int, int]]] = {}
        for mention in graph.mentions:
            if not (0 <= mention.query_id < qc):
                raise ValueError(
                    f"sample={bi} mention query_id {mention.query_id} "
                    f"outside query_count {qc}"
                )
            if not (0 <= mention.start < mention.end <= tl):
                raise ValueError(
                    f"sample={bi} mention [{mention.start}, {mention.end}) "
                    f"out of range for length {tl}"
                )
            pairs = per_query.setdefault(mention.query_id, [])
            pair = (mention.start, mention.end)
            if pair not in pairs:
                pairs.append(pair)
        observed_max = max(
            observed_max, max((len(pairs) for pairs in per_query.values()), default=0)
        )
        grouped_mentions.append(per_query)

    if max_gold_per_query is None:
        g = max(observed_max, 1)
    else:
        if max_gold_per_query <= 0:
            raise ValueError("max_gold_per_query must be > 0 or None")
        g = max_gold_per_query

    mention_pairs = torch.zeros(b, q, g, 2, dtype=torch.long, device=device)
    mention_mask = torch.zeros(b, q, g, dtype=torch.bool, device=device)
    truncated_pairs = 0
    skipped_samples = 0

    for bi, per_query in enumerate(grouped_mentions):
        # skip_sample: if any query overflows, drop this sample's gold entirely.
        if on_capacity_exceeded == "skip_sample" and any(
            len(pairs) > g for pairs in per_query.values()
        ):
            overflow = {qi: len(p) for qi, p in per_query.items() if len(p) > g}
            logger.warning(
                "sample=%d skipped: gold capacity exceeded (max_gold_per_query=%d, "
                "overflowing queries=%s)", bi, g, overflow
            )
            skipped_samples += 1
            continue

        for qi, pairs in per_query.items():
            if len(pairs) > g:
                if on_capacity_exceeded == "raise":
                    raise TargetCapacityError(
                        f"sample={bi} query_id={qi} contains {len(pairs)} gold spans, "
                        f"but max_gold_per_query={g}. Increase "
                        "boundary_head.max_gold_per_query and "
                        "boundary_head.training_candidate_budget."
                    )
                # truncate_with_warning
                dropped = len(pairs) - g
                truncated_pairs += dropped
                logger.warning(
                    "sample=%d query_id=%d truncated %d gold span(s) to fit "
                    "max_gold_per_query=%d", bi, qi, dropped, g
                )
                pairs = pairs[:g]
            count = len(pairs)
            if count:
                mention_pairs[bi, qi, :count] = torch.as_tensor(
                    pairs, dtype=torch.long, device=device
                )
                mention_mask[bi, qi, :count] = True

    if truncated_pairs:
        logger.warning(
            "pad_target_graphs truncated %d gold span(s) across the batch "
            "(on_capacity_exceeded='truncate_with_warning')", truncated_pairs
        )
    if skipped_samples:
        logger.warning(
            "pad_target_graphs skipped %d sample(s) for gold capacity "
            "(on_capacity_exceeded='skip_sample')", skipped_samples
        )

    records = [list(graph.records) for graph in graphs]
    has_records = any(records)
    start_targets = end_targets = inside_targets = None
    if build_dense:
        from cognee.tasks.graph.gliner_demo.onnx._gliner2.models.boundary.targets_device import dense_targets_from_pairs

        start_targets, end_targets, inside_targets = dense_targets_from_pairs(
            mention_pairs, mention_mask, l
        )
    return PaddedTargetBatch(
        mention_pairs=mention_pairs,
        mention_mask=mention_mask,
        start_targets=start_targets,
        end_targets=end_targets,
        inside_targets=inside_targets,
        records=records if has_records else None,
    )


# =============================================================================
# Truncation policy
# =============================================================================

def apply_truncation_policy(
    graph: TargetGraph,
    truncated_length: int,
    policy: str,
) -> Optional[TargetGraph]:
    """Apply a truncation policy to mentions that cross ``truncated_length``.

    Policies:
      * ``"error"``        - raise if any mention ends beyond the truncation.
      * ``"drop_target"``  - drop only mentions that cross the boundary.
      * ``"drop_example"`` - return ``None`` if any mention crosses.
    """
    if policy not in ("error", "drop_target", "drop_example"):
        raise ValueError(f"unknown truncation policy {policy!r}")
    crossing = [m for m in graph.mentions if m.end > truncated_length]
    if not crossing:
        return graph
    if policy == "error":
        raise ValueError(
            f"{len(crossing)} gold mention(s) cross truncation length "
            f"{truncated_length}; span [{crossing[0].start}, {crossing[0].end})"
        )
    if policy == "drop_example":
        return None
    kept = tuple(m for m in graph.mentions if m.end <= truncated_length)
    return TargetGraph(
        mentions=kept,
        choices=graph.choices,
        instances=graph.instances,
        edges=graph.edges,
        literals=graph.literals,
        records=graph.records,
    )
