# Copied from gliner2 2.0.0 (inference/overlap.py), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
"""Shared deterministic overlap-policy normalization and resolution.

The resolver is deliberately independent of torch and model-specific candidate
types so local inference, boundary decoding, chunk merging, and the API client
all use the same explicit semantics.
"""

from __future__ import annotations

import bisect
from typing import Callable, List, Optional, Sequence, TypeVar


T = TypeVar("T")

_ALIASES = {
    "allow": "allow",
    "all": "allow",
    "none": "allow",
    "nested": "nested",
    "allow_nested": "nested",
    "flat": "disallow",
    "disallow": "disallow",
    "no_overlap": "disallow",
    "non_overlapping": "disallow",
    "longest": "longest",
    "keep_longest": "longest",
}


def normalize_overlap_policy(
    policy: Optional[str],
    *,
    default: Optional[str] = None,
) -> str:
    """Return a canonical overlap policy.

    ``None`` is resolved only through ``default``. This lets callers preserve
    architecture defaults instead of accidentally imposing a shared default.
    """
    selected = default if policy is None else policy
    if selected is None:
        raise ValueError("overlap_policy=None requires an architecture default")
    if not isinstance(selected, str):
        raise TypeError("overlap_policy must be a string or None")
    key = selected.strip().lower().replace("-", "_")
    try:
        return _ALIASES[key]
    except KeyError as exc:
        supported = "allow, nested, flat/disallow, longest"
        raise ValueError(
            f"unknown overlap_policy {selected!r}; expected one of: {supported}"
        ) from exc


def resolve_overlaps(
    items: Sequence[T],
    policy: Optional[str],
    *,
    score: Callable[[T], float],
    start: Callable[[T], int],
    end: Callable[[T], int],
    default: Optional[str] = None,
) -> List[T]:
    """Resolve half-open spans with deterministic, shared semantics.

    Policies are applied after exact-boundary duplicates are collapsed to their
    highest-ranked representative:

    * ``allow`` keeps every distinct span.
    * ``nested`` keeps disjoint and containment overlaps, rejecting crossings.
    * ``flat``/``disallow`` returns the maximum-total-score non-overlapping set.
    * ``longest`` drops spans strictly contained by another candidate.

    Results are always ranked by descending score, then ascending start/end.
    """
    canonical = normalize_overlap_policy(policy, default=default)
    if not items:
        return []

    indexed = list(enumerate(items))

    def rank_key(row):
        index, item = row
        return (-float(score(item)), int(start(item)), int(end(item)), index)

    ranked = sorted(indexed, key=rank_key)
    distinct = []
    seen_boundaries = set()
    for row in ranked:
        item = row[1]
        boundaries = (int(start(item)), int(end(item)))
        if boundaries in seen_boundaries:
            continue
        seen_boundaries.add(boundaries)
        distinct.append(row)

    if canonical == "allow":
        return [item for _, item in distinct]

    if canonical == "nested":
        kept = []
        for row in distinct:
            candidate = row[1]
            candidate_start = int(start(candidate))
            candidate_end = int(end(candidate))
            crossing = False
            for _, existing in kept:
                existing_start = int(start(existing))
                existing_end = int(end(existing))
                overlaps = (
                    candidate_start < existing_end
                    and existing_start < candidate_end
                )
                contains = (
                    candidate_start <= existing_start
                    and existing_end <= candidate_end
                ) or (
                    existing_start <= candidate_start
                    and candidate_end <= existing_end
                )
                if overlaps and not contains:
                    crossing = True
                    break
            if not crossing:
                kept.append(row)
        return [item for _, item in kept]

    if canonical == "longest":
        kept = []
        for row in distinct:
            candidate = row[1]
            candidate_start = int(start(candidate))
            candidate_end = int(end(candidate))
            strictly_contained = any(
                int(start(other)) <= candidate_start
                and candidate_end <= int(end(other))
                and (
                    int(start(other)) < candidate_start
                    or candidate_end < int(end(other))
                )
                for _, other in distinct
            )
            if not strictly_contained:
                kept.append(row)
        return [item for _, item in kept]

    # Weighted interval scheduling for canonical ``disallow``. Dynamic-program
    # ties prefer the lexicographically better confidence/start/end ranking.
    by_end = sorted(
        distinct,
        key=lambda row: (
            int(end(row[1])),
            int(start(row[1])),
            -float(score(row[1])),
            row[0],
        ),
    )
    ends = [int(end(item)) for _, item in by_end]
    predecessors = [
        bisect.bisect_right(ends, int(start(item)), 0, index) - 1
        for index, (_, item) in enumerate(by_end)
    ]
    best: List[tuple[float, tuple[int, ...]]] = [(0.0, ())]

    def selection_key(selection: tuple[int, ...]):
        rows = [by_end[index] for index in selection]
        return tuple(rank_key(row) for row in sorted(rows, key=rank_key))

    for index, (_, item) in enumerate(by_end):
        previous_score, previous_selection = best[predecessors[index] + 1]
        with_item = (
            previous_score + float(score(item)),
            previous_selection + (index,),
        )
        without_item = best[index]
        if with_item[0] > without_item[0]:
            best.append(with_item)
        elif with_item[0] < without_item[0]:
            best.append(without_item)
        elif len(with_item[1]) > len(without_item[1]):
            # Missing confidences are represented as zero during chunk merge;
            # keep the largest compatible set instead of selecting nothing.
            best.append(with_item)
        elif len(with_item[1]) < len(without_item[1]):
            best.append(without_item)
        else:
            best.append(
                with_item
                if selection_key(with_item[1]) < selection_key(without_item[1])
                else without_item
            )

    selected = [by_end[index] for index in best[-1][1]]
    selected.sort(key=rank_key)
    return [item for _, item in selected]


__all__ = ["normalize_overlap_policy", "resolve_overlaps"]
