"""Reusable harness for the migration/model lockstep guard.

The fresh-database bootstrap builds the schema with ``create_all()`` from
``Base.metadata`` and then STAMPS Alembic head — asserting, without checking,
that the models and the migration chain describe the same schema. This module
makes that assertion checkable in CI: build a frozen, certified snapshot of the
model schema as a real database, stamp it at the snapshot's revision, replay
only the migrations added since, and compare the result against the current
models in both directions.

It lives in the runtime package (not under ``tests/``) so downstream
deployments that vendor their own Alembic chain — e.g. cognee cloud, whose
chain, model surface, and certified baseline all differ from upstream's — can
reuse it verbatim, varying only:

- ``register_models``: a callable importing every model module that deployment
  actually registers (the upstream default walks ``cognee.modules.*.models``;
  a deployment adds its own model imports on top);
- ``script_location``: the Alembic scripts directory (defaults to cognee's
  packaged chain; a vendored chain passes its own path);
- the frozen baseline file, generated by ``generate_baseline`` at that
  deployment's own certified revision.

See ``cognee/tests/integration/infrastructure/relational/
test_migration_model_lockstep.py`` for the upstream wiring and the
re-freezing rules.
"""

import importlib
import json
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Optional

import sqlalchemy as sa
from sqlalchemy import inspect

# Alembic's own bookkeeping lives outside the models on purpose.
DEFAULT_IGNORED_TABLES = frozenset({"alembic_version"})


def register_upstream_models() -> None:
    """Import every ``cognee.modules.<x>.models`` package so ``Base.metadata``
    is complete and deterministic — importing the API surface registers most
    models as a side effect, but not all of them (e.g. the integrations and
    sync models), and a schema snapshot must not depend on which corner of
    cognee a process happened to touch first.

    Only the package ``__init__`` is imported, deliberately: that is the set a
    real process registers, so it is the set ``create_all`` actually builds.
    Orphaned model files a package does not export (e.g. the unimportable
    ``pipelines/models/Task.py``) are not part of any real schema.
    """
    import cognee.modules

    root = Path(cognee.modules.__file__).parent
    for sub in sorted(path.name for path in root.iterdir() if path.is_dir()):
        if (root / sub / "models" / "__init__.py").exists():
            importlib.import_module(f"cognee.modules.{sub}.models")


def collect_model_schema(
    register_models: Callable[[], None] = register_upstream_models,
) -> dict[str, list[str]]:
    """Tables and column names ``Base.metadata`` declares, after registering
    the deployment's full model surface."""
    register_models()
    from cognee.infrastructure.databases.relational import Base

    return {
        table.name: sorted(column.name for column in table.columns)
        for table in Base.metadata.sorted_tables
    }


def current_head(script_location: str | None = None) -> str:
    from alembic.script import ScriptDirectory

    from cognee.modules.migrations.startup import _build_alembic_config

    return ScriptDirectory.from_config(_build_alembic_config(script_location)).get_current_head()


def revision_exists(revision: str, script_location: str | None = None) -> bool:
    from alembic.script import ScriptDirectory

    from cognee.modules.migrations.startup import _build_alembic_config

    script = ScriptDirectory.from_config(_build_alembic_config(script_location))
    try:
        return script.get_revision(revision) is not None
    except Exception:
        return False


def generate_baseline(
    path: Path,
    register_models: Callable[[], None] = register_upstream_models,
    script_location: str | None = None,
) -> dict:
    """Freeze the current model schema at the current chain head. A deliberate
    act only: regenerating a baseline erases the guard's memory, so it must be
    accompanied by a re-certification that a real chain-migrated database
    matches the models exactly."""
    baseline = {
        "baseline_revision": current_head(script_location),
        "tables": collect_model_schema(register_models),
    }
    path.write_text(json.dumps(baseline, indent=2, sort_keys=True) + "\n")
    return baseline


def load_baseline(path: Path) -> dict:
    return json.loads(path.read_text())


async def replay_from_baseline(
    baseline: dict,
    database_url: str,
    script_location: str | None = None,
    ignored_tables: Iterable[str] = DEFAULT_IGNORED_TABLES,
) -> dict[str, list[str]]:
    """Build the baseline snapshot as a real database stamped at the baseline
    revision, replay every migration above it through cognee's own runner, and
    reflect the resulting tables and column names.

    Column types in the snapshot are generic (the comparison is by NAME);
    what matters is that the migrations added since the freeze run for real
    against a base that predates them.
    """
    from unittest.mock import patch

    from cognee.infrastructure.databases.relational.sqlalchemy.SqlAlchemyAdapter import (
        SQLAlchemyAdapter,
    )
    from cognee.modules.migrations.startup import run_relational_migrations

    adapter = SQLAlchemyAdapter(database_url)
    ignored = set(ignored_tables)

    try:
        async with adapter.engine.begin() as connection:

            def _create(sync_connection):
                metadata = sa.MetaData()
                for name, columns in baseline["tables"].items():
                    sa.Table(name, metadata, *(sa.Column(col, sa.Text()) for col in columns))
                metadata.create_all(sync_connection)

            await connection.run_sync(_create)
            await connection.execute(
                sa.text(
                    "CREATE TABLE alembic_version (version_num VARCHAR(32) NOT NULL, "
                    "CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num))"
                )
            )
            await connection.execute(
                sa.text("INSERT INTO alembic_version VALUES (:revision)"),
                {"revision": baseline["baseline_revision"]},
            )

        # The replay must run against THIS database, whatever the ambient
        # config says: run_relational_migrations resolves its engine through
        # get_relational_engine, so pin it for the duration of the replay.
        with patch(
            "cognee.infrastructure.databases.relational.get_relational_engine",
            return_value=adapter,
        ):
            await run_relational_migrations("head", script_location)

        async with adapter.engine.connect() as connection:
            return await connection.run_sync(
                lambda sync_conn: {
                    table: sorted(
                        column["name"] for column in inspect(sync_conn).get_columns(table)
                    )
                    for table in inspect(sync_conn).get_table_names()
                    if table not in ignored
                }
            )
    finally:
        await adapter.engine.dispose()


def compare_schemas(expected: dict[str, list[str]], actual: dict[str, list[str]]) -> list[str]:
    """Describe every disagreement between the model schema (``expected``) and
    the chain-built schema (``actual``), in both directions. Empty = lockstep."""
    problems = []
    for table in sorted(set(actual) - set(expected)):
        problems.append(
            f"the chain creates table '{table}' that no model declares "
            "(migration landed without its model change?)"
        )
    for table in sorted(set(expected) - set(actual)):
        problems.append(
            f"models declare table '{table}' that no migration creates "
            "(model change landed without its migration?)"
        )
    for table in sorted(set(actual) & set(expected)):
        extra = sorted(set(actual[table]) - set(expected[table]))
        missing = sorted(set(expected[table]) - set(actual[table]))
        if extra:
            problems.append(
                f"table '{table}': the chain adds column(s) {extra} the models do not "
                "declare — fresh databases built by create_all will LACK them while "
                "stamped as having them (the mis-stamp incident direction)"
            )
        if missing:
            problems.append(
                f"table '{table}': models declare column(s) {missing} that no migration "
                "adds — existing databases will never receive them on upgrade"
            )
    return problems
