# Copied from gliner2 2.0.0 (models/candidates.py), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
"""Architecture-neutral per-sample candidate containers.

A ``CandidateSet`` is the decoded, per-(sample, query) view of sparse span
candidates in half-open ``[start, end)`` token coordinates. Both the span
adapter and the boundary model produce these so downstream decoding/formatting
is architecture-independent.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Sequence, Tuple

from cognee.tasks.graph.gliner_demo.onnx import _tensor as torch


@dataclass(frozen=True)
class ScoredSpanCandidate:
    """A single scored half-open span candidate for one query."""
    query_id: int
    start: int
    end: int
    logit: float
    probability: float

    def __post_init__(self) -> None:
        if self.end <= self.start:
            raise ValueError(
                f"half-open span requires end > start, got [{self.start}, {self.end})"
            )


@dataclass
class CandidateSet:
    """All surviving candidates for a single (batch sample) across its queries.

    Coordinates are half-open token boundaries. ``starts``/``ends``/``logits``
    are 1-D tensors of equal length ``N``; ``query_ids`` maps each candidate to
    its query index within the sample.
    """
    query_ids: torch.LongTensor          # [N]
    starts: torch.LongTensor             # [N]
    ends: torch.LongTensor               # [N]
    logits: torch.Tensor                 # [N]

    def __post_init__(self) -> None:
        n = self.starts.shape[0]
        for name in ("query_ids", "ends", "logits"):
            t = getattr(self, name)
            if t.shape[0] != n:
                raise ValueError(
                    f"CandidateSet field {name!r} has length {t.shape[0]}, expected {n}"
                )

    def __len__(self) -> int:
        return int(self.starts.shape[0])

    def to(self, device) -> "CandidateSet":
        return CandidateSet(
            query_ids=self.query_ids.to(device),
            starts=self.starts.to(device),
            ends=self.ends.to(device),
            logits=self.logits.to(device),
        )

    def for_query(self, query_id: int) -> List[Tuple[int, int, float]]:
        """Return ``(start, end, logit)`` triples for one query, in stored order."""
        mask = self.query_ids == query_id
        idx = torch.nonzero(mask, as_tuple=False).flatten().tolist()
        return [
            (int(self.starts[i]), int(self.ends[i]), float(self.logits[i]))
            for i in idx
        ]

    def unique_spans(self) -> set:
        """Set of ``(query_id, start, end)`` tuples (for oracle/recall checks)."""
        return {
            (int(self.query_ids[i]), int(self.starts[i]), int(self.ends[i]))
            for i in range(len(self))
        }
