# Copied from gliner2 2.0.0 (training/trainer.py (ExtractorCollator only)), Apache-2.0,
# https://github.com/fastino-ai/GLiNER2. Regenerated by vendor_gliner2.py;
# only import lines differ from upstream. Do not edit by hand.
from __future__ import annotations

from typing import Dict, List, Optional, Tuple


class ExtractorCollator:
    """Data collator that converts raw records to model inputs."""

    def __init__(
            self, processor: SchemaTransformer, is_training: bool = True,
            max_len=None, architecture: str = "span",
            max_gold_per_query: Optional[int] = 32,
            build_targets: Optional[bool] = None,
            on_capacity_exceeded: str = "raise",
            allow_invalid_samples: bool = False,
    ):
        self.processor = processor
        self.is_training = is_training
        self.max_len = max_len
        self.architecture = architecture
        self.max_gold_per_query = max_gold_per_query
        # For an eval collator (``is_training=False``) set ``build_targets=True``
        # so a supervised eval loss can be computed while the model runs in eval
        # mode. Defaults to ``is_training`` (plain inference builds no targets).
        self.build_targets = build_targets
        # Gold-capacity overflow policy (raise | truncate_with_warning |
        # skip_sample); defaults to the no-silent-loss "raise".
        self.on_capacity_exceeded = on_capacity_exceeded
        self.allow_invalid_samples = allow_invalid_samples

    def __call__(self, batch: List[Tuple[str, Dict]]):
        """
        Convert batch of (text, schema) tuples to PreprocessedBatch.

        Args:
            batch: List of (text, schema) tuples from dataset

        Returns:
            PreprocessedBatch ready for model.forward()
        """
        if self.is_training:
            kwargs = dict(
                max_len=self.max_len, architecture=self.architecture,
                max_gold_per_query=self.max_gold_per_query,
                on_capacity_exceeded=self.on_capacity_exceeded,
            )
            if self.allow_invalid_samples:
                kwargs.update(
                    error_policy="skip",
                    ignore_missing_entities=True,
                )
            return self.processor.collate_fn_train(batch, **kwargs)
        else:
            kwargs = dict(
                max_len=self.max_len, architecture=self.architecture,
                build_targets=self.build_targets,
                max_gold_per_query=self.max_gold_per_query,
                on_capacity_exceeded=self.on_capacity_exceeded,
            )
            if self.allow_invalid_samples:
                kwargs.update(
                    error_policy="skip",
                    ignore_missing_entities=True,
                )
            return self.processor.collate_fn_inference(batch, **kwargs)
