"""Tests for the POSIX parent-death ARM-WINDOW race in `run_worker_loop`.

Root cause this fixes: `set_pdeathsig()` arms `prctl(PR_SET_PDEATHSIG,
SIGTERM)` from INSIDE the child, at the top of `run_worker_loop`.
`PR_SET_PDEATHSIG` is not retroactive -- it only fires for a parent death that
happens AFTER the prctl call. Workers here are `spawn`-started, so there is a
real window (re-exec python, import chain, unpickle) between `Process.start()`
in the parent and the arm in the child. A parent that dies in that window (an
OOM kill being the realistic trigger) delivers no signal, ever. Worse,
`set_pdeathsig()` returns True regardless -- the syscall itself succeeded --
which SUPPRESSES the `start_parent_liveness_watchdog()` fallback at the call
site. Net result: an orphaned worker holding an exclusive Kuzu/LanceDB lock
forever. This is the POSIX twin of the Windows orphan incident that
`test_windows_parent_death_watchdog.py` covers.

Why these tests are structured the way they are:

* Real `spawn`/`forkserver` subprocesses running the REAL `run_worker_loop`,
  and a real `SIGKILL` of a real parent. The bug is entirely about kernel
  process lifecycle; a mock of `prctl` or of `parent_process()` would test the
  mock, not the guarantee.
* The parent kills ITSELF with `SIGKILL` rather than being killed from the
  test process, so the death is indistinguishable from an OOM kill (no
  handlers, no atexit, no chance to clean up its children).
* The worker deliberately stalls before entering `run_worker_loop`, which
  widens the naturally microsecond-wide arm window into a deterministic one.
  Without the stall this race reproduces only by luck.
* Liveness is pinned to ONE process via `/proc/<pid>/stat` field 22
  (`starttime`), never by PID number alone -- otherwise PID reuse could make a
  dead worker look alive (false failure) or, in the survival test, make a
  reused PID look like a surviving worker (false PASS, the dangerous
  direction).

`TestNoFalsePositive` is the load-bearing regression guard for the OTHER
failure mode: the naive version of this fix ("compare `os.getppid()` to the
launch-time parent pid") reports "parent dead" for a perfectly healthy parent
under the `forkserver` start method, where the two differ BY DESIGN because
the child's OS parent is the fork server, not the launching process. CPython
3.14 makes `forkserver` the default on Linux, so that naive fix would
`os._exit(0)` every worker at startup. Those tests must keep passing under
`forkserver` specifically.
"""

from __future__ import annotations

import os
import queue as _queue
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    sys.platform != "linux", reason="POSIX parent-death race; /proc and prctl are Linux-only"
)

# Derived from the module under test rather than hard-coded, so the suite also
# runs from a copied tree (e.g. a WSL native-filesystem scratch copy).
_REPO_ROOT = str(Path(__file__).resolve().parents[2])

# Long enough that the parent is reliably dead before the worker reaches
# ``run_worker_loop``; short enough to keep the suite quick.
_STALL_SECONDS = 5.0
_KILL_AFTER_SECONDS = 1.5

_PARENT_SCRIPT = '''\
"""Generated by test_linux_parent_death_race.py. Stands in for the real
main process that owns a cognee_db_workers subprocess session."""
import multiprocessing as mp
import os
import signal
import sys
import time

sys.path.insert(0, {repo_root!r})

from cognee_db_workers.harness import run_worker_loop

STALL = {stall!r}
METHOD = {method!r}
KILL_MODE = {kill_mode!r}
KILL_AFTER = {kill_after!r}


def _worker(req_q, resp_q):
    # The deliberate stall. In production this window is filled by spawn's own
    # re-exec + import + unpickle work; here it is explicit so the race is
    # deterministic rather than a microsecond-wide coin flip.
    time.sleep(STALL)
    # The REAL loop -- not a stand-in. Empty dispatch + no init is enough: the
    # arming block under test runs before either is touched.
    run_worker_loop({{}}, req_q, resp_q)


if __name__ == "__main__":
    ctx = mp.get_context(METHOD)
    req_q = ctx.Queue()
    resp_q = ctx.Queue()
    # daemon=True mirrors the real KuzuSubprocessSession/LanceDB spawn. It is
    # NOT a safety net here: daemon children are reaped by the parent's atexit
    # handler, which a SIGKILLed parent never runs.
    proc = ctx.Process(target=_worker, args=(req_q, resp_q), daemon=True)
    proc.start()
    print("PID %d" % proc.pid, flush=True)

    if KILL_MODE == "during_arm_window":
        # Die while the worker is still stalling, i.e. BEFORE it can arm
        # pdeathsig. SIGKILL to self == OOM-killer semantics.
        time.sleep(KILL_AFTER)
        print("KILLING_SELF", flush=True)
        os.kill(os.getpid(), signal.SIGKILL)

    # Every other mode needs the worker fully up first.
    try:
        resp_q.get(timeout=30)
        print("READY", flush=True)
    except Exception as exc:
        print("NO_READY %s" % type(exc).__name__, flush=True)

    if KILL_MODE == "after_arm":
        time.sleep(KILL_AFTER)
        print("KILLING_SELF", flush=True)
        os.kill(os.getpid(), signal.SIGKILL)

    # KILL_MODE == "never": stay alive so the worker's survival can be
    # observed against a genuinely healthy parent.
    time.sleep(120)
'''


def _proc_identity(pid: int):
    """``(state, starttime)`` from ``/proc/<pid>/stat``, or ``None`` if gone.

    ``starttime`` (field 22, clock ticks since boot) is what makes this
    PID-reuse-proof: it is fixed for the life of one process, so a PID that has
    been recycled by an unrelated process reports a different value and is
    correctly treated as "the process we were watching is gone".

    Field 2 (``comm``) is an arbitrary string wrapped in parentheses and may
    itself contain spaces and parentheses, so parsing starts after the LAST
    ``)``. The remaining whitespace-separated tokens begin at field 3, hence
    field N is at index ``N - 3``: state -> 0, starttime -> 19.
    """
    try:
        with open("/proc/%d/stat" % pid, "rb") as fh:
            raw = fh.read()
    except (FileNotFoundError, ProcessLookupError, PermissionError):
        return None
    try:
        fields = raw[raw.rindex(b")") + 1 :].split()
        return fields[0].decode(), fields[19].decode()
    except (ValueError, IndexError):
        return None


def _require_identity(pid: int) -> str:
    ident = _proc_identity(pid)
    assert ident is not None, f"worker pid {pid} was already gone when the test tried to pin it"
    return ident[1]


def _is_gone(pid: int, starttime: str) -> bool:
    """True once THAT specific process is no longer running.

    Zombies count as gone: the worker has exited: it is merely un-reaped
    because its parent is dead. A different ``starttime`` means the PID was
    recycled, which also means the original is gone.
    """
    ident = _proc_identity(pid)
    if ident is None:
        return True
    state, current_starttime = ident
    if current_starttime != starttime:
        return True
    return state == "Z"


class _LineReader:
    """Non-blocking line access to a child's stdout.

    ``readline()`` on a pipe blocks forever if the writer dies without writing,
    which would hang the whole suite instead of failing it. A reader thread
    plus a queue turns that into a bounded, reportable timeout.
    """

    def __init__(self, proc: subprocess.Popen):
        self._q: "_queue.Queue[str]" = _queue.Queue()
        self._proc = proc
        self._t = threading.Thread(target=self._pump, daemon=True)
        self._t.start()

    def _pump(self) -> None:
        try:
            for line in self._proc.stdout:
                self._q.put(line.strip())
        except Exception:
            pass

    def next_line(self, timeout: float = 30.0) -> str:
        try:
            return self._q.get(timeout=timeout)
        except _queue.Empty:
            raise AssertionError(
                f"parent process printed no further output within {timeout}s "
                f"(exit code so far: {self._proc.poll()})"
            )


def _write_parent_script(tmp_path, *, method: str, kill_mode: str, stall: float) -> str:
    path = tmp_path / f"parent_{method}_{kill_mode}.py"
    path.write_text(
        _PARENT_SCRIPT.format(
            repo_root=_REPO_ROOT,
            stall=stall,
            method=method,
            kill_mode=kill_mode,
            kill_after=_KILL_AFTER_SECONDS,
        )
    )
    return str(path)


def _launch_parent(script: str) -> subprocess.Popen:
    return subprocess.Popen(
        [sys.executable, script],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )


def _reap(pid: int) -> None:
    try:
        os.kill(pid, signal.SIGKILL)
    except (ProcessLookupError, PermissionError, OSError):
        pass


class TestArmWindowRace:
    """The reported bug: parent dies BEFORE the worker can arm pdeathsig."""

    @pytest.mark.parametrize("method", ["spawn", "forkserver"])
    def test_worker_exits_when_parent_dies_before_pdeathsig_is_armed(self, tmp_path, method):
        script = _write_parent_script(
            tmp_path, method=method, kill_mode="during_arm_window", stall=_STALL_SECONDS
        )
        parent = _launch_parent(script)
        worker_pid = None
        try:
            reader = _LineReader(parent)
            line = reader.next_line()
            assert line.startswith("PID "), f"unexpected first line from parent: {line!r}"
            worker_pid = int(line.split()[1])
            starttime = _require_identity(worker_pid)

            assert reader.next_line() == "KILLING_SELF"
            parent.wait(timeout=15)
            assert parent.returncode == -signal.SIGKILL, (
                f"parent did not die by SIGKILL (returncode={parent.returncode}); "
                "the race was never actually set up"
            )

            # Budget: the remaining stall, plus generous slack for a loaded box.
            deadline = time.monotonic() + _STALL_SECONDS + 25.0
            while time.monotonic() < deadline:
                if _is_gone(worker_pid, starttime):
                    return
                time.sleep(0.1)
            pytest.fail(
                f"[{method}] worker pid {worker_pid} was STILL RUNNING "
                f"{_STALL_SECONDS + 25.0:.0f}s after its parent was SIGKILLed during the "
                "pdeathsig arm window. This is the orphaned-worker-holding-a-DB-lock bug: "
                "prctl(PR_SET_PDEATHSIG) is not retroactive, and set_pdeathsig() returning "
                "True suppresses the polling-watchdog fallback."
            )
        finally:
            if worker_pid is not None:
                _reap(worker_pid)
            if parent.poll() is None:
                parent.kill()


class TestNoFalsePositive:
    """The forkserver regression guard.

    A healthy parent must never cause a worker to exit. This is exactly what
    the naive `os.getppid() != launch_ppid` fix breaks: under `forkserver` the
    worker's OS parent is the fork server, so `getppid()` differs from the
    launching process's pid permanently, with the parent in perfect health --
    measured on this target (WSL Ubuntu / CPython 3.14.4), parent alive
    throughout::

        spawn        parent_process().pid=199682  getppid()=199682
        fork         parent_process().pid=199682  getppid()=199682
        forkserver   parent_process().pid=199682  getppid()=199706   <-- differ

    If someone re-introduces that comparison as the PRIMARY signal, the
    forkserver parametrisation below fails: every worker exits at startup.
    """

    @pytest.mark.parametrize("method", ["spawn", "fork", "forkserver"])
    def test_worker_survives_while_parent_is_alive(self, tmp_path, method):
        script = _write_parent_script(tmp_path, method=method, kill_mode="never", stall=0.0)
        parent = _launch_parent(script)
        worker_pid = None
        try:
            reader = _LineReader(parent)
            line = reader.next_line()
            assert line.startswith("PID "), f"unexpected first line from parent: {line!r}"
            worker_pid = int(line.split()[1])
            starttime = _require_identity(worker_pid)

            status = reader.next_line()
            assert status == "READY", (
                f"[{method}] worker never reported READY ({status!r}) -- it exited or hung "
                "during startup even though its parent is alive. Under forkserver this is "
                "the signature of a getppid()-based parent-death check firing on a healthy "
                "parent."
            )

            # Watch for a while: a false positive kills the worker essentially
            # immediately, so a steady 6s is a decisive observation.
            deadline = time.monotonic() + 6.0
            while time.monotonic() < deadline:
                assert not _is_gone(worker_pid, starttime), (
                    f"[{method}] worker pid {worker_pid} exited while its parent was still "
                    "alive -- parent_already_exited() produced a FALSE POSITIVE. This is the "
                    "outage-shaped failure mode: every worker dies at startup."
                )
                time.sleep(0.25)
            assert parent.poll() is None, "the parent died on its own; test setup is invalid"
        finally:
            if worker_pid is not None:
                _reap(worker_pid)
            if parent.poll() is None:
                parent.kill()


class TestNormalPathNotRegressed:
    """pdeathsig must still do its job when the parent dies AFTER arming.

    `spawn` only, deliberately, and NOT because forkserver is untested here --
    `TestArmWindowRace` covers forkserver and passes. It is because under
    `forkserver` this assertion is simply not true of the code, and measuring
    it is how that was established. `prctl(PR_SET_PDEATHSIG)` anchors to the
    caller's OS parent, and under `forkserver` the worker's OS parent is the
    FORK SERVER, not the launching process. Measured on WSL Ubuntu / CPython
    3.14.4, launching process SIGKILLed at t=3s::

        forkserver  worker=200042  os_parent(getppid)=200041 (fork server)
                                   mp_parent_process_pid=200039 (real parent)
        t= 2.00  os_parent(200041)=alive  real_parent(200039)=alive  sentinel=True
        t= 4.00  os_parent(200041)=alive  real_parent(200039)=GONE   sentinel=False
        t=18.00  os_parent(200041)=alive  real_parent(200039)=GONE   sentinel=False
        SURVIVED_FULL_20s

    The fork server outlived the launching process (it was merely reparented,
    200039 -> 200008), so the worker's pdeathsig never fired and the worker
    orphaned. That is a SECOND, pre-existing gap, distinct from the arm-window
    race this change fixes, and it is out of scope here: cognee's real workers
    pin `mp.get_context("spawn")` explicitly (kuzu and lancedb
    `subprocess/proxy.py`), so the forkserver anchoring gap is latent, not
    live. Note the sentinel column above -- it read the real parent's death
    correctly at t=4 in exactly the case prctl could not, which is why
    `parent_already_exited` is built on the sentinel and not on prctl or
    getppid.

    No characterization test asserts the survival above: doing so would lock
    the bug in and go red the day someone fixes it properly.
    """

    @pytest.mark.parametrize("method", ["spawn"])
    def test_pdeathsig_kills_worker_when_parent_dies_after_arming(self, tmp_path, method):
        script = _write_parent_script(tmp_path, method=method, kill_mode="after_arm", stall=0.0)
        parent = _launch_parent(script)
        worker_pid = None
        try:
            reader = _LineReader(parent)
            line = reader.next_line()
            assert line.startswith("PID "), f"unexpected first line from parent: {line!r}"
            worker_pid = int(line.split()[1])
            starttime = _require_identity(worker_pid)

            # READY proves the worker got past the arming block, so the death
            # below lands strictly AFTER prctl armed -- the normal path.
            assert reader.next_line() == "READY"
            assert reader.next_line() == "KILLING_SELF"
            parent.wait(timeout=15)
            assert parent.returncode == -signal.SIGKILL

            deadline = time.monotonic() + 20.0
            while time.monotonic() < deadline:
                if _is_gone(worker_pid, starttime):
                    return
                time.sleep(0.1)
            pytest.fail(
                f"[{method}] worker pid {worker_pid} survived its parent's SIGKILL even though "
                "pdeathsig was armed before the parent died -- the kernel parent-death signal "
                "path has regressed."
            )
        finally:
            if worker_pid is not None:
                _reap(worker_pid)
            if parent.poll() is None:
                parent.kill()


class TestParentAlreadyExitedUnitSemantics:
    """Fail-safe contract of the helpers, without spawning anything."""

    def test_returns_false_without_a_baseline(self):
        from cognee_db_workers import harness

        # Not a multiprocessing child at all: no sentinel, no baseline pid.
        # Must NOT claim the parent is dead.
        assert harness.get_original_parent_pid() is None
        assert harness.parent_already_exited(None) is False

    def test_returns_false_on_win32_regardless_of_baseline(self, monkeypatch):
        from cognee_db_workers import harness

        monkeypatch.setattr(harness.sys, "platform", "win32")
        assert harness.parent_already_exited(999999) is False
        assert harness.parent_already_exited(None) is False

    def test_sentinel_absent_reports_unknown_not_dead(self):
        from cognee_db_workers import harness

        # In the main process there is no parent sentinel; the tri-state must
        # be None ("cannot tell"), never False ("dead").
        assert harness._parent_sentinel_alive() is None

    def test_getppid_fallback_is_not_used_under_forkserver(self, monkeypatch):
        """The naive fix, contained.

        Even in the fallback branch (no usable sentinel), the `getppid()`
        comparison must be refused under `forkserver`, where it is
        structurally meaningless. A bogus baseline pid that "differs" from
        `getppid()` must still yield False.
        """
        import multiprocessing

        from cognee_db_workers import harness

        monkeypatch.setattr(harness, "_parent_sentinel_alive", lambda: None)
        bogus_baseline = 999999
        assert os.getppid() != bogus_baseline

        monkeypatch.setattr(multiprocessing, "get_start_method", lambda allow_none=False: "forkserver")
        assert harness.parent_already_exited(bogus_baseline) is False, (
            "getppid() comparison must be refused under forkserver -- it differs from the "
            "real parent pid by design there, so trusting it kills healthy workers"
        )

        # ...but it IS the intended last resort under spawn.
        monkeypatch.setattr(multiprocessing, "get_start_method", lambda allow_none=False: "spawn")
        assert harness.parent_already_exited(bogus_baseline) is True
