SOURCE_REF_PREFIX = "source_ref:v1"
SOURCE_RUN_REF_PREFIX = "source_run_ref:v1"

GRAPH_PROVENANCE_VERSION_KEY = "provenance_version"
GRAPH_DELETE_MODE_KEY = "delete_mode"
GRAPH_PROVENANCE_VERSION = "1"
GRAPH_DELETE_MODE_GRAPH_NATIVE = "graph_native"
