---
apiVersion: v2
name: cognee-chart
description: Helm chart for deploying the cognee backend on Kubernetes

type: application

version: 0.2.0
appVersion: "1.2.2"

maintainers:
  - name: topoteretes
    url: https://github.com/topoteretes/cognee
