name: community | Greetings

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  greeting:
    if: github.actor != 'github-actions[bot]' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d  # v3.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: |
          Hello @${{ github.actor }}, thank you for your interest in our work!

          If this is a bug report, please provide screenshots and **minimum viable code to reproduce your issue**, otherwise we can not help you.
