name: Reusable Examples Tests

on:
  workflow_call:
    inputs:
      examples:
        required: false
        type: string
        default: "all"
        description: "Which examples to run (comma-separated list or 'all')"

jobs:
  run-examples-tests:
    name: Example Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - multimetric-qa
          - graphrag-vs-rag
          - multimedia
          - deduplication
          - eval-framework
          - descriptive-graph-metrics
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          
      - name: Install dependencies
        run: poetry install --no-interaction --all-extras
        
      - name: Run Multi-metric QA Example
        if: matrix.example == 'multimetric-qa'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
          GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
        run: poetry run python ./examples/python/multimetric_qa_eval_run.py
        
      - name: Run GraphRAG vs RAG Example
        if: matrix.example == 'graphrag-vs-rag'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
          GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
        run: poetry run python ./examples/python/graphrag_vs_rag.py
        
      - name: Run Multimedia Example
        if: matrix.example == 'multimedia'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
          GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
        run: poetry run python ./examples/python/multimedia_example.py
        
      - name: Run Deduplication Example
        if: matrix.example == 'deduplication'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
          GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
        run: poetry run python ./examples/python/deduplication.py
        
      - name: Run Evaluation Framework Example
        if: matrix.example == 'eval-framework'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
          GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
        run: poetry run python ./examples/python/eval_framework.py
        
      - name: Run Descriptive Graph Metrics Example
        if: matrix.example == 'descriptive-graph-metrics'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
          GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
        run: poetry run python ./examples/python/descriptive_graph_metrics.py 