name: Reusable Notebook Tests

on:
  workflow_call:
    inputs:
      include-all:
        required: false
        type: boolean
        default: true
        description: "Whether to run all notebook tests"
    secrets:
      inherit: true

jobs:
  run-main-notebook:
    name: Main Notebook Test
    uses: ./.github/workflows/reusable_notebook.yml
    with:
      notebook-location: notebooks/cognee_demo.ipynb
    secrets: inherit
    
  run-llama-index-integration:
    name: LlamaIndex Integration Notebook
    needs: run-main-notebook
    if: ${{ inputs.include-all || success() }}
    uses: ./.github/workflows/test_llama_index_cognee_integration_notebook.yml
    secrets: inherit
    
  run-cognee-llama-index:
    name: Cognee LlamaIndex Notebook
    needs: run-main-notebook
    if: ${{ inputs.include-all || success() }}
    uses: ./.github/workflows/test_cognee_llama_index_notebook.yml
    secrets: inherit
    
  run-cognee-multimedia:
    name: Cognee Multimedia Notebook
    needs: run-main-notebook
    if: ${{ inputs.include-all || success() }}
    uses: ./.github/workflows/test_cognee_multimedia_notebook.yml
    secrets: inherit 