name: test | bedrock | aws profile

on:
  workflow_call:

jobs:
  test-bedrock-aws-profile:
    name: Run Bedrock AWS Profile Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cognee Setup
        uses: ./.github/actions/cognee_setup
        with:
          python-version: '3.11.x'

      - name: Configure AWS Profile
        run: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOF
          [bedrock-test]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

      - name: Run Bedrock AWS Profile Test
        env:
          LLM_PROVIDER: "bedrock"
          LLM_MODEL: "us.anthropic.claude-3-5-haiku-20241022-v1:0"
          AWS_PROFILE_NAME: "bedrock-test"
          AWS_REGION_NAME: "us-east-1"
          EMBEDDING_PROVIDER: "bedrock"
          EMBEDDING_MODEL: "amazon.titan-embed-text-v2:0"
          EMBEDDING_DIMENSIONS: "1024"
        run: poetry run python ./examples/python/simple_example.py
