name: test | llama index notebook

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_notebook_test:
      uses: ./.github/workflows/reusable_notebook.yml
      with:
        notebook-location: notebooks/cognee_llama_index.ipynb
      secrets:
        #LLM_MODEL: ${{ secrets.LLM_MODEL }}
        #LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
        LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        #LLM_API_VERSION: ${{ secrets.LLM_API_VERSION }}
        EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
        EMBEDDING_ENDPOINT: ${{ secrets.EMBEDDING_ENDPOINT }}
        EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
        EMBEDDING_API_VERSION: ${{ secrets.EMBEDDING_API_VERSION }}
        GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
        GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
