name: Test Suites

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUNTIME__LOG_LEVEL: ERROR
  ENV: 'dev'

jobs:
  basic-tests:
    name: Basic Tests
    uses: ./.github/workflows/reusable_basic_tests.yml
    secrets: inherit

  integration-tests:
    name: Integration Tests
    uses: ./.github/workflows/reusable_integration_tests.yml
    secrets: inherit

  graph-db-tests:
    name: Graph Database Tests
    needs: [basic-tests, integration-tests]
    uses: ./.github/workflows/reusable_graph_db_tests.yml
    secrets: inherit

  notebook-tests:
    name: Notebook Tests
    needs: [basic-tests, integration-tests]
    uses: ./.github/workflows/reusable_notebooks_tests.yml
    secrets: inherit

  python-version-tests:
    name: Python Version Tests
    needs: [basic-tests, integration-tests]
    uses: ./.github/workflows/reusable_python_version_tests.yml
    secrets: inherit

  # Matrix-based vector database tests
  vector-db-tests:
    name: Vector DB Tests
    needs: [basic-tests, integration-tests]
    uses: ./.github/workflows/reusable_vector_db_tests.yml
    secrets: inherit

  # Matrix-based example tests
  example-tests:
    name: Example Tests
    needs: [basic-tests, integration-tests]
    uses: ./.github/workflows/reusable_examples_tests.yml
    secrets: inherit

  # Additional LLM tests
  gemini-tests:
    name: Gemini Tests
    needs: [basic-tests, integration-tests]
    uses: ./.github/workflows/test_gemini.yml
    secrets: inherit

  # Ollama tests moved to the end
  ollama-tests:
    name: Ollama Tests
    needs: [
      basic-tests,
      integration-tests,
      graph-db-tests,
      notebook-tests,
      python-version-tests,
      vector-db-tests,
      example-tests,
      gemini-tests
    ]
    uses: ./.github/workflows/reusable_ollama_tests.yml
    secrets: inherit

  notify:
    name: Test Completion Status
    needs: [
      basic-tests,
      integration-tests,
      graph-db-tests,
      notebook-tests,
      python-version-tests,
      vector-db-tests,
      example-tests,
      gemini-tests,
      ollama-tests
    ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Status
        run: |
          if [[ "${{ needs.basic-tests.result }}" == "success" &&
                "${{ needs.integration-tests.result }}" == "success" &&
                "${{ needs.graph-db-tests.result }}" == "success" &&
                "${{ needs.notebook-tests.result }}" == "success" &&
                "${{ needs.python-version-tests.result }}" == "success" &&
                "${{ needs.vector-db-tests.result }}" == "success" &&
                "${{ needs.example-tests.result }}" == "success" &&
                "${{ needs.gemini-tests.result }}" == "success" &&
                "${{ needs.ollama-tests.result }}" == "success" ]]; then
            echo "All test suites completed successfully!"
          else
            echo "One or more test suites failed."
            exit 1
          fi
