name: test | openrouter

on:
  workflow_call:

jobs:
  test-openrouter:
    name: Run OpenRouter Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cognee Setup
        uses: ./.github/actions/cognee_setup
        with:
          python-version: '3.11.x'

      - name: Run OpenRouter Simple Example
        env:
          LLM_PROVIDER: "custom"
          LLM_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          LLM_MODEL: "openrouter/x-ai/grok-code-fast-1"
          LLM_ENDPOINT: "https://openrouter.ai/api/v1"
          EMBEDDING_PROVIDER: "openai"
          EMBEDDING_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBEDDING_MODEL: "openai/text-embedding-3-large"
          EMBEDDING_DIMENSIONS: "3072"
          EMBEDDING_MAX_TOKENS: "8191"
        run: uv run python ./examples/python/simple_example.py
