name: test

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_notebook_test_windows:
    name: windows-latest
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --all-extras

      - name: Execute Python Example
        env:
          ENV: 'dev'
          PYTHONFAULTHANDLER: 1
          LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: poetry run python ./examples/python/dynamic_steps_example.py
